#ifndef EXP_CONVEX_COST_MANAGER_HPP
#define EXP_CONVEX_COST_MANAGER_HPP

#include "traj_opt/convex_hull/convex_hull.hpp"
#include "traj_opt/costfunctional/spatialcosts/polytope_position_penalty.hpp"
#include "traj_opt/costfunctional/spatialcosts/squared_norm_bound_penalty.hpp"
#include "traj_opt/costfunctional_manager/exp_integal_cost_manager.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <vector>

namespace cost_functional_manager
{
/**
 * State2state corridor cost manager using a control-point cost functional.
 *
 * Every source segment is converted to subdivided Bezier position controls
 * exactly once. Physical-time derivative controls are then generated by the
 * Bezier hodograph recurrence
 *
 *   B_i^(r) = (n-r+1) / T_leaf * (B_(i+1)^(r-1)-B_i^(r-1)).
 *
 * The adjoint follows the same difference chain in reverse, so position,
 * velocity, acceleration and jerk costs require one power-to-Bezier operator
 * and one final MINCO coefficient adjoint. MINVO costs are obtained by a small
 * degree-local Bezier-to-MINVO basis change after the hodograph; they do not
 * trigger independent source-polynomial conversions.
 *
 * Non-polynomial costs (guide path, swarm, angular rate and thrust) retain the
 * original dense evaluator. MINCOOptimizer can completely skip dense sampling
 * when none of those residual terms is active.
 */
class ExpConvexCostManager
{
public:
  using Basis = traj_opt::convex_hull::Basis;

  void configure(Basis basis,
                 int subdivision_depth,
                 int cost_version = 1)
  {
    basis_ = basis;
    subdivision_depth_ = std::clamp(subdivision_depth, 0, 8);
    cost_version_ = std::clamp(cost_version, 1, 2);
  }

  void reset(const general_utils::PolyhedraH *h_polys,
             const Eigen::VectorXi *h_poly_idx,
             const general_utils::Mat3Df *waypoint_attractors,
             const general_utils::VecDf *waypoint_attractor_dead_d,
             double smooth_eps,
             const general_utils::VecDf &magnitude_bounds,
             const general_utils::VecDf &penalty_weights,
             flatness::FlatnessMap *quadrotor_flatness,
             const traj_opt::SwarmPenaltyConfig &swarm_config,
             const traj_opt::SwarmTrajectoriesConstPtr &swarm_trajs,
             double swarm_current_wall_time,
             const general_utils::vec_E<general_utils::Vec3f> *guide_path = nullptr,
             const std::vector<double> *guide_t = nullptr,
             double weight_guide_integral = 0.0,
             double guide_path_tube_radius = 0.0,
             double guide_path_z_tube_radius = 0.0,
             double guide_path_huber_delta = 0.0,
             bool guide_path_time_gradient_en = false)
  {
    h_polys_ = h_polys;
    h_poly_idx_ = h_poly_idx;
    smooth_eps_ = std::max(1.0e-6, smooth_eps);
    magnitude_bounds_ = magnitude_bounds;
    penalty_weights_ = penalty_weights;

    general_utils::VecDf residual_weights = penalty_weights;
    const int polynomial_weight_count =
        std::min<int>(4, residual_weights.size());
    residual_weights.head(polynomial_weight_count).setZero();
    residual_cost_manager_.reset(h_polys,
                                 h_poly_idx,
                                 waypoint_attractors,
                                 waypoint_attractor_dead_d,
                                 smooth_eps,
                                 magnitude_bounds,
                                 residual_weights,
                                 quadrotor_flatness,
                                 swarm_config,
                                 swarm_trajs,
                                 swarm_current_wall_time,
                                 guide_path,
                                 guide_t,
                                 weight_guide_integral,
                                 guide_path_tube_radius,
                                 guide_path_z_tube_radius,
                                 guide_path_huber_delta,
                                 guide_path_time_gradient_en);

    const bool attractor_active =
        residual_weights.size() > 4 && residual_weights(4) > 0.0;
    const bool angular_rate_active =
        residual_weights.size() > 5 && residual_weights(5) > 0.0;
    const bool thrust_active =
        residual_weights.size() > 6 && residual_weights(6) > 0.0;
    const bool guide_active = weight_guide_integral > 0.0;
    const bool swarm_active =
        swarm_trajs != nullptr &&
        ((swarm_config.enable && swarm_config.weight > 0.0) ||
         (swarm_config.formation_enable &&
          swarm_config.formation_weight > 0.0));
    dense_sampling_required_ = attractor_active || angular_rate_active ||
                               thrust_active || guide_active || swarm_active;
  }

  bool usesDenseSampling() const
  {
    return dense_sampling_required_;
  }

  std::size_t activeControlPointChecksPerEvaluation() const
  {
    if (!bezier_hull_.kernel())
    {
      return 0;
    }
    std::size_t checks = 0;
    for (int derivative_order = 0; derivative_order <= 3;
         ++derivative_order)
    {
      if (penalty_weights_.size() > derivative_order &&
          penalty_weights_(derivative_order) > 0.0)
      {
        if (cost_version_ == 2 && basis_ == Basis::Bezier)
        {
          const int cp = controlsPerPiece(derivative_order);
          const int unique_per_segment =
              bezier_hull_.piecesPerSegment() * (cp - 1) + 1;
          checks += static_cast<std::size_t>(
              bezier_hull_.numSourceSegments() * unique_per_segment);
        }
        else
        {
          checks += static_cast<std::size_t>(
              selected_controls_[derivative_order].rows());
        }
      }
    }
    return checks;
  }

  void beginEvaluation(const std::vector<double> *times)
  {
    residual_cost_manager_.beginEvaluation(times);
    hull_violation_.setZero(9);
  }

  const general_utils::VecDf &getPenaltyLog() const
  {
    combined_penalty_log_ = residual_cost_manager_.getPenaltyLog();
    if (combined_penalty_log_.size() < hull_violation_.size())
    {
      combined_penalty_log_.conservativeResize(hull_violation_.size());
    }
    for (int i = 1; i <= 4; ++i)
    {
      combined_penalty_log_(i) =
          std::max(combined_penalty_log_(i), hull_violation_(i));
    }
    return combined_penalty_log_;
  }

  double guideIntegralViolation() const
  {
    return residual_cost_manager_.guideIntegralViolation();
  }

  double guideCostLog() const
  {
    return residual_cost_manager_.guideCostLog();
  }

  double guideMaxAbsTimeGrad() const
  {
    return residual_cost_manager_.guideMaxAbsTimeGrad();
  }

  int guideOutOfTimeRangeSamples() const
  {
    return residual_cost_manager_.guideOutOfTimeRangeSamples();
  }

  double evaluateIntegral(int logical_idx,
                          double t_local,
                          double t_global,
                          int seg_idx,
                          int step_in_seg,
                          const Eigen::Vector3d &position,
                          const Eigen::Vector3d &velocity,
                          const Eigen::Vector3d &acceleration,
                          const Eigen::Vector3d &jerk,
                          Eigen::Vector3d &grad_position,
                          Eigen::Vector3d &grad_velocity,
                          Eigen::Vector3d &grad_acceleration,
                          Eigen::Vector3d &grad_jerk,
                          double &grad_time) const
  {
    return residual_cost_manager_.evaluateIntegral(logical_idx,
                                                   t_local,
                                                   t_global,
                                                   seg_idx,
                                                   step_in_seg,
                                                   position,
                                                   velocity,
                                                   acceleration,
                                                   jerk,
                                                   grad_position,
                                                   grad_velocity,
                                                   grad_acceleration,
                                                   grad_jerk,
                                                   grad_time);
  }

  template <typename SampleBuffer>
  double evaluateSample(const SampleBuffer &samples,
                        Eigen::Matrix<double, 3, Eigen::Dynamic> &grad_position,
                        Eigen::VectorXd &grad_time) const
  {
    return residual_cost_manager_.evaluateSample(
        samples, grad_position, grad_time);
  }

  template <typename Trajectory>
  double evaluateCoefficient(
      const Trajectory &trajectory,
      typename Trajectory::CoeffMat &grad_coefficients,
      Eigen::VectorXd &grad_durations) const
  {
    if (!ready())
    {
      return 0.0;
    }

    updateControlPoints(trajectory);
    const Eigen::VectorXd &durations = trajectory.getDurations();

    double cost = accumulatePositionCost(durations, grad_durations);
    for (int derivative_order = 1; derivative_order <= 3;
         ++derivative_order)
    {
      cost += accumulateDerivativeCost(durations,
                                       derivative_order,
                                       grad_durations);
    }

    backwardControlPointGradients(durations, grad_durations);
    bezier_hull_.backwardAdd(bezier_gradients_[0],
                             grad_coefficients,
                             grad_durations);
    return cost;
  }

private:
  using Hull = traj_opt::convex_hull::Representation<3>;
  using HullMatrix = typename Hull::Matrix;

  bool ready() const
  {
    return h_polys_ != nullptr &&
           h_poly_idx_ != nullptr &&
           magnitude_bounds_.size() >= 3 &&
           penalty_weights_.size() >= 4;
  }

  int controlsPerPiece(int derivative_order) const
  {
    return bezier_hull_.sourceDegree() + 1 - derivative_order;
  }

  template <typename Trajectory>
  void updateControlPoints(const Trajectory &trajectory) const
  {
    const bool topology_changed =
        !bezier_hull_.kernel() ||
        bezier_hull_.numSourceSegments() != trajectory.getPieceNum() ||
        bezier_hull_.sourceNumCoeffs() != Trajectory::COEFF_NUM ||
        bezier_hull_.subdivisionDepth() != subdivision_depth_ ||
        cached_output_basis_ != basis_;
    if (topology_changed)
    {
      bezier_hull_.resetTopology(trajectory.getPieceNum(),
                                 Trajectory::COEFF_NUM,
                                 Basis::Bezier,
                                 0,
                                 subdivision_depth_);
      cached_output_basis_ = basis_;
      const int num_pieces = bezier_hull_.numPieces();
      for (int derivative_order = 0; derivative_order <= 3;
           ++derivative_order)
      {
        const int degree = bezier_hull_.sourceDegree() - derivative_order;
        const int cp = degree + 1;
        bezier_controls_[derivative_order].resize(num_pieces * cp, 3);
        selected_controls_[derivative_order].resize(num_pieces * cp, 3);
        bezier_gradients_[derivative_order].resize(num_pieces * cp, 3);
        selected_gradients_[derivative_order].resize(num_pieces * cp, 3);

        if (basis_ == Basis::Bezier)
        {
          basis_change_[derivative_order] =
              Eigen::MatrixXd::Identity(cp, cp);
        }
        else
        {
          const Eigen::MatrixXd bezier_power_to_control =
              Hull::powerToControlMatrix(Basis::Bezier, degree);
          const Eigen::MatrixXd minvo_power_to_control =
              Hull::powerToControlMatrix(Basis::MINVO, degree);
          basis_change_[derivative_order] =
              minvo_power_to_control *
              bezier_power_to_control.inverse();
        }
      }
    }

    trajectory.updateConvexHull(bezier_hull_);
    bezier_controls_[0] = bezier_hull_.controls();
    const Eigen::VectorXd &durations = trajectory.getDurations();
    const int leaves = bezier_hull_.piecesPerSegment();
    for (int derivative_order = 1; derivative_order <= 3;
         ++derivative_order)
    {
      const int previous_cp = controlsPerPiece(derivative_order - 1);
      const int current_cp = previous_cp - 1;
      const double degree_factor = static_cast<double>(previous_cp - 1);
      for (int piece = 0; piece < bezier_hull_.numPieces(); ++piece)
      {
        const int segment = bezier_hull_.pieceInfo(piece).source_segment;
        const double hodograph_scale =
            degree_factor * static_cast<double>(leaves) /
            durations(segment);
        const int previous_row = piece * previous_cp;
        const int current_row = piece * current_cp;
        for (int control = 0; control < current_cp; ++control)
        {
          bezier_controls_[derivative_order].row(current_row + control) =
              hodograph_scale *
              (bezier_controls_[derivative_order - 1]
                   .row(previous_row + control + 1) -
               bezier_controls_[derivative_order - 1]
                   .row(previous_row + control));
        }
      }
    }

    for (int derivative_order = 0; derivative_order <= 3;
         ++derivative_order)
    {
      const int cp = controlsPerPiece(derivative_order);
      if (basis_ == Basis::Bezier)
      {
        selected_controls_[derivative_order] =
            bezier_controls_[derivative_order];
      }
      else
      {
        for (int piece = 0; piece < bezier_hull_.numPieces(); ++piece)
        {
          selected_controls_[derivative_order]
              .middleRows(piece * cp, cp)
              .noalias() =
              basis_change_[derivative_order] *
              bezier_controls_[derivative_order]
                  .middleRows(piece * cp, cp);
        }
      }
      bezier_gradients_[derivative_order].setZero();
      selected_gradients_[derivative_order].setZero();
    }
  }

  double accumulatePositionCost(
      const Eigen::VectorXd &durations,
      Eigen::VectorXd &direct_duration_gradients) const
  {
    if (cost_version_ == 2 && basis_ == Basis::Bezier)
    {
      return accumulatePositionCostV2(durations,
                                      direct_duration_gradients);
    }

    const double weight = std::max(0.0, penalty_weights_(0));
    if (weight <= 0.0)
    {
      return 0.0;
    }

    double cost = 0.0;
    const int controls_per_piece = controlsPerPiece(0);
    for (int piece = 0; piece < bezier_hull_.numPieces(); ++piece)
    {
      const int segment = bezier_hull_.pieceInfo(piece).source_segment;
      if (segment < 0 || segment >= h_poly_idx_->size())
      {
        continue;
      }
      const int poly_id = (*h_poly_idx_)(segment);
      if (poly_id < 0 || poly_id >= static_cast<int>(h_polys_->size()))
      {
        continue;
      }
      const double scale =
          durations(segment) /
          static_cast<double>(bezier_hull_.piecesPerSegment() *
                              controls_per_piece);
      for (int control = 0; control < controls_per_piece; ++control)
      {
        const int row = piece * controls_per_piece + control;
        const Eigen::Vector3d value =
            selected_controls_[0].row(row).transpose();
        Eigen::Vector3d gradient = Eigen::Vector3d::Zero();
        const double local_cost =
            cost_functional::accumulatePolytopePositionPenalty(
                (*h_polys_)[poly_id],
                value,
                smooth_eps_,
                weight * scale,
                gradient,
                &hull_violation_(1));
        selected_gradients_[0].row(row) += gradient.transpose();
        direct_duration_gradients(segment) +=
            local_cost / durations(segment);
        cost += local_cost;
      }
    }
    return cost;
  }

  double accumulateDerivativeCost(
      const Eigen::VectorXd &durations,
      int derivative_order,
      Eigen::VectorXd &direct_duration_gradients) const
  {
    if (cost_version_ == 2 && basis_ == Basis::Bezier)
    {
      return accumulateDerivativeCostV2(durations,
                                        derivative_order,
                                        direct_duration_gradients);
    }

    const double weight =
        std::max(0.0, penalty_weights_(derivative_order));
    const double bound = magnitude_bounds_(derivative_order - 1);
    if (weight <= 0.0 || !std::isfinite(bound) || bound <= 0.0)
    {
      return 0.0;
    }

    double cost = 0.0;
    const int controls_per_piece = controlsPerPiece(derivative_order);
    for (int piece = 0; piece < bezier_hull_.numPieces(); ++piece)
    {
      const int segment = bezier_hull_.pieceInfo(piece).source_segment;
      const double scale =
          durations(segment) /
          static_cast<double>(bezier_hull_.piecesPerSegment() *
                              controls_per_piece);
      for (int control = 0; control < controls_per_piece; ++control)
      {
        const int row = piece * controls_per_piece + control;
        const Eigen::Vector3d value =
            selected_controls_[derivative_order].row(row).transpose();
        Eigen::Vector3d gradient = Eigen::Vector3d::Zero();
        const double local_cost =
            cost_functional::accumulateSquaredNormBoundPenalty(
                value,
                bound * bound,
                smooth_eps_,
                weight * scale,
                gradient,
                &hull_violation_(derivative_order + 1));
        selected_gradients_[derivative_order].row(row) +=
            gradient.transpose();
        direct_duration_gradients(segment) +=
            local_cost / durations(segment);
        cost += local_cost;
      }
    }
    return cost;
  }

  double accumulatePositionCostV2(
      const Eigen::VectorXd &durations,
      Eigen::VectorXd &direct_duration_gradients) const
  {
    const double weight = std::max(0.0, penalty_weights_(0));
    if (weight <= 0.0)
    {
      return 0.0;
    }

    double cost = 0.0;
    const int leaves = bezier_hull_.piecesPerSegment();
    const int controls_per_piece = controlsPerPiece(0);

    for (int segment = 0;
         segment < bezier_hull_.numSourceSegments();
         ++segment)
    {
      if (segment >= h_poly_idx_->size())
      {
        continue;
      }
      const int poly_id = (*h_poly_idx_)(segment);
      if (poly_id < 0 || poly_id >= static_cast<int>(h_polys_->size()))
      {
        continue;
      }
      const double duration = durations(segment);
      const double base_scale =
          duration /
          static_cast<double>(leaves * controls_per_piece);
      for (int leaf = 0; leaf < leaves; ++leaf)
      {
        const int piece = segment * leaves + leaf;
        const int first_control = leaf == 0 ? 0 : 1;
        for (int control = first_control;
             control < controls_per_piece;
             ++control)
        {
          const int row = piece * controls_per_piece + control;
          // The last control of every non-final leaf is exactly the first
          // control of the next leaf. Fold both identical V1 terms into this
          // row instead of evaluating the same penalty twice.
          const double multiplicity =
              control == controls_per_piece - 1 && leaf + 1 < leaves
                  ? 2.0
                  : 1.0;
          const Eigen::Vector3d value =
              selected_controls_[0].row(row).transpose();
          Eigen::Vector3d gradient = Eigen::Vector3d::Zero();
          const double local_cost =
              cost_functional::accumulatePolytopePositionPenalty(
                  (*h_polys_)[poly_id],
                  value,
                  smooth_eps_,
                  weight * base_scale * multiplicity,
                  gradient,
                  &hull_violation_(1));
          selected_gradients_[0].row(row) += gradient.transpose();
          direct_duration_gradients(segment) += local_cost / duration;
          cost += local_cost;
        }
      }
    }
    return cost;
  }

  double accumulateDerivativeCostV2(
      const Eigen::VectorXd &durations,
      int derivative_order,
      Eigen::VectorXd &direct_duration_gradients) const
  {
    const double weight =
        std::max(0.0, penalty_weights_(derivative_order));
    const double bound = magnitude_bounds_(derivative_order - 1);
    if (weight <= 0.0 || !std::isfinite(bound) || bound <= 0.0)
    {
      return 0.0;
    }

    double cost = 0.0;
    const int leaves = bezier_hull_.piecesPerSegment();
    const int controls_per_piece = controlsPerPiece(derivative_order);

    for (int segment = 0;
         segment < bezier_hull_.numSourceSegments();
         ++segment)
    {
      const double duration = durations(segment);
      const double base_scale =
          duration /
          static_cast<double>(leaves * controls_per_piece);
      for (int leaf = 0; leaf < leaves; ++leaf)
      {
        const int piece = segment * leaves + leaf;
        const int first_control = leaf == 0 ? 0 : 1;
        for (int control = first_control;
             control < controls_per_piece;
             ++control)
        {
          const int row = piece * controls_per_piece + control;
          const double multiplicity =
              control == controls_per_piece - 1 && leaf + 1 < leaves
                  ? 2.0
                  : 1.0;
          const Eigen::Vector3d value =
              selected_controls_[derivative_order].row(row).transpose();
          Eigen::Vector3d gradient = Eigen::Vector3d::Zero();
          const double local_cost =
              cost_functional::accumulateSquaredNormBoundPenalty(
                  value,
                  bound * bound,
                  smooth_eps_,
                  weight * base_scale * multiplicity,
                  gradient,
                  &hull_violation_(derivative_order + 1));
          selected_gradients_[derivative_order].row(row) +=
              gradient.transpose();
          direct_duration_gradients(segment) += local_cost / duration;
          cost += local_cost;
        }
      }
    }
    return cost;
  }

  void backwardControlPointGradients(
      const Eigen::VectorXd &durations,
      Eigen::VectorXd &direct_duration_gradients) const
  {
    for (int derivative_order = 0; derivative_order <= 3;
         ++derivative_order)
    {
      const int cp = controlsPerPiece(derivative_order);
      if (basis_ == Basis::Bezier)
      {
        bezier_gradients_[derivative_order] =
            selected_gradients_[derivative_order];
      }
      else
      {
        for (int piece = 0; piece < bezier_hull_.numPieces(); ++piece)
        {
          bezier_gradients_[derivative_order]
              .middleRows(piece * cp, cp)
              .noalias() =
              basis_change_[derivative_order].transpose() *
              selected_gradients_[derivative_order]
                  .middleRows(piece * cp, cp);
        }
      }
    }

    const int leaves = bezier_hull_.piecesPerSegment();
    for (int derivative_order = 3; derivative_order >= 1;
         --derivative_order)
    {
      const int current_cp = controlsPerPiece(derivative_order);
      const int previous_cp = current_cp + 1;
      const double degree_factor = static_cast<double>(previous_cp - 1);
      for (int piece = 0; piece < bezier_hull_.numPieces(); ++piece)
      {
        const int segment = bezier_hull_.pieceInfo(piece).source_segment;
        const double duration = durations(segment);
        const double hodograph_scale =
            degree_factor * static_cast<double>(leaves) / duration;
        const int current_row = piece * current_cp;
        const int previous_row = piece * previous_cp;

        direct_duration_gradients(segment) -=
            bezier_gradients_[derivative_order]
                .middleRows(current_row, current_cp)
                .cwiseProduct(bezier_controls_[derivative_order]
                                  .middleRows(current_row, current_cp))
                .sum() /
            duration;

        for (int control = 0; control < current_cp; ++control)
        {
          const auto gradient =
              bezier_gradients_[derivative_order]
                  .row(current_row + control);
          bezier_gradients_[derivative_order - 1]
              .row(previous_row + control) -= hodograph_scale * gradient;
          bezier_gradients_[derivative_order - 1]
              .row(previous_row + control + 1) += hodograph_scale * gradient;
        }
      }
    }
  }

  ExpIntegralCostManager residual_cost_manager_;
  const general_utils::PolyhedraH *h_polys_{nullptr};
  const Eigen::VectorXi *h_poly_idx_{nullptr};
  double smooth_eps_{1.0e-3};
  general_utils::VecDf magnitude_bounds_;
  general_utils::VecDf penalty_weights_;
  Basis basis_{Basis::Bezier};
  mutable Basis cached_output_basis_{Basis::Bezier};
  int subdivision_depth_{0};
  int cost_version_{1};
  bool dense_sampling_required_{true};

  mutable Hull bezier_hull_;
  mutable std::array<Eigen::MatrixXd, 4> basis_change_;
  mutable std::array<HullMatrix, 4> bezier_controls_;
  mutable std::array<HullMatrix, 4> selected_controls_;
  mutable std::array<HullMatrix, 4> bezier_gradients_;
  mutable std::array<HullMatrix, 4> selected_gradients_;
  mutable general_utils::VecDf hull_violation_{
      general_utils::VecDf::Zero(9)};
  mutable general_utils::VecDf combined_penalty_log_{
      general_utils::VecDf::Zero(9)};
};
} // namespace cost_functional_manager

#endif
