# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from aperture_detector/ApertureObservation.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class ApertureObservation(genpy.Message):
  _md5sum = "95d12957350e43dfd81355376a355b51"
  _type = "aperture_detector/ApertureObservation"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# Geometry only: validity does not certify vehicle passage or free exit space.
# stamp is the newest contributing cloud stamp, never a publication timestamp.
std_msgs/Header header
bool geometry_valid
string reason
geometry_msgs/Point center
geometry_msgs/Vector3 normal
geometry_msgs/Polygon boundary
float64 plane_area
float64 hole_area
float64 area_ratio
bool visual_roi_used
bool depth_known
float64 depth

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Polygon
#A specification of a polygon where the first and last points are assumed to be connected
Point32[] points

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z"""
  __slots__ = ['header','geometry_valid','reason','center','normal','boundary','plane_area','hole_area','area_ratio','visual_roi_used','depth_known','depth']
  _slot_types = ['std_msgs/Header','bool','string','geometry_msgs/Point','geometry_msgs/Vector3','geometry_msgs/Polygon','float64','float64','float64','bool','bool','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,geometry_valid,reason,center,normal,boundary,plane_area,hole_area,area_ratio,visual_roi_used,depth_known,depth

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ApertureObservation, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.geometry_valid is None:
        self.geometry_valid = False
      if self.reason is None:
        self.reason = ''
      if self.center is None:
        self.center = geometry_msgs.msg.Point()
      if self.normal is None:
        self.normal = geometry_msgs.msg.Vector3()
      if self.boundary is None:
        self.boundary = geometry_msgs.msg.Polygon()
      if self.plane_area is None:
        self.plane_area = 0.
      if self.hole_area is None:
        self.hole_area = 0.
      if self.area_ratio is None:
        self.area_ratio = 0.
      if self.visual_roi_used is None:
        self.visual_roi_used = False
      if self.depth_known is None:
        self.depth_known = False
      if self.depth is None:
        self.depth = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.geometry_valid = False
      self.reason = ''
      self.center = geometry_msgs.msg.Point()
      self.normal = geometry_msgs.msg.Vector3()
      self.boundary = geometry_msgs.msg.Polygon()
      self.plane_area = 0.
      self.hole_area = 0.
      self.area_ratio = 0.
      self.visual_roi_used = False
      self.depth_known = False
      self.depth = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.geometry_valid
      buff.write(_get_struct_B().pack(_x))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6d().pack(_x.center.x, _x.center.y, _x.center.z, _x.normal.x, _x.normal.y, _x.normal.z))
      length = len(self.boundary.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.boundary.points:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_3d2Bd().pack(_x.plane_area, _x.hole_area, _x.area_ratio, _x.visual_roi_used, _x.depth_known, _x.depth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.center is None:
        self.center = geometry_msgs.msg.Point()
      if self.normal is None:
        self.normal = geometry_msgs.msg.Vector3()
      if self.boundary is None:
        self.boundary = geometry_msgs.msg.Polygon()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.geometry_valid,) = _get_struct_B().unpack(str[start:end])
      self.geometry_valid = bool(self.geometry_valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.center.x, _x.center.y, _x.center.z, _x.normal.x, _x.normal.y, _x.normal.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.boundary.points = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.boundary.points.append(val1)
      _x = self
      start = end
      end += 34
      (_x.plane_area, _x.hole_area, _x.area_ratio, _x.visual_roi_used, _x.depth_known, _x.depth,) = _get_struct_3d2Bd().unpack(str[start:end])
      self.visual_roi_used = bool(self.visual_roi_used)
      self.depth_known = bool(self.depth_known)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.geometry_valid
      buff.write(_get_struct_B().pack(_x))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6d().pack(_x.center.x, _x.center.y, _x.center.z, _x.normal.x, _x.normal.y, _x.normal.z))
      length = len(self.boundary.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.boundary.points:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_3d2Bd().pack(_x.plane_area, _x.hole_area, _x.area_ratio, _x.visual_roi_used, _x.depth_known, _x.depth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.center is None:
        self.center = geometry_msgs.msg.Point()
      if self.normal is None:
        self.normal = geometry_msgs.msg.Vector3()
      if self.boundary is None:
        self.boundary = geometry_msgs.msg.Polygon()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.geometry_valid,) = _get_struct_B().unpack(str[start:end])
      self.geometry_valid = bool(self.geometry_valid)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.center.x, _x.center.y, _x.center.z, _x.normal.x, _x.normal.y, _x.normal.z,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.boundary.points = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.boundary.points.append(val1)
      _x = self
      start = end
      end += 34
      (_x.plane_area, _x.hole_area, _x.area_ratio, _x.visual_roi_used, _x.depth_known, _x.depth,) = _get_struct_3d2Bd().unpack(str[start:end])
      self.visual_roi_used = bool(self.visual_roi_used)
      self.depth_known = bool(self.depth_known)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d2Bd = None
def _get_struct_3d2Bd():
    global _struct_3d2Bd
    if _struct_3d2Bd is None:
        _struct_3d2Bd = struct.Struct("<3d2Bd")
    return _struct_3d2Bd
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
