#############| For swarm UAV simulation |#################################
pcd_name: "big_field.pcd"
mesh_resource: "package://perfect_drone_sim/meshes/yunque-M.dae"
cmd_topic: "/drone_0/planning/pos_cmd"
odom_topic: "/drone_0/lidar_slam/odom"
pose_topic: "/drone_0/lidar_slam/pose"
local_pc_topic: "/drone_0/cloud_registered"
global_pc_topic: "/drone_0/global_pc"
robot_frame_id: "drone_0/base_link"
init_position:
  x: -2.5
  y: 0.0
  z: 1.5
init_yaw: 0.0

#############|For LiDAR perception simulation |#################################
is_360lidar: true
polar_resolution: 0.4
downsample_res: 0.1
vertical_fov: 178.0
sensing_blind: 0.1
sensing_horizon: 70
sensing_rate: 10
print_time_consumption: false
lidar_type: 2
depth_image_en: false
