# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from person_tracker/FusionStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class FusionStatus(genpy.Message):
  _md5sum = "cef58aa4031f7412f2f67a529906fd39"
  _type = "person_tracker/FusionStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """uint8 WAITING=0
uint8 LOCKED=1
uint8 SUSPECT=2
uint8 LOST=3

uint8 UNKNOWN=0
uint8 OUT_OF_VIEW=1
uint8 CONSISTENT=2
uint8 CONFLICT=3

std_msgs/Header header
uint8 fusion_state
string fusion_state_text
uint8 semantic_evidence
string semantic_evidence_text
bool camera_projection_valid
bool predicted_in_fov
bool yolo_target_present
bool yolo_lidar_component_valid
bool automatic_reselection_eligible
bool reselection_ready
uint32 conflict_count
uint32 confirmation_count
float64 semantic_distance
float64 semantic_age
int32 target_id
string reason

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  # Pseudo-constants
  WAITING = 0
  LOCKED = 1
  SUSPECT = 2
  LOST = 3
  UNKNOWN = 0
  OUT_OF_VIEW = 1
  CONSISTENT = 2
  CONFLICT = 3

  __slots__ = ['header','fusion_state','fusion_state_text','semantic_evidence','semantic_evidence_text','camera_projection_valid','predicted_in_fov','yolo_target_present','yolo_lidar_component_valid','automatic_reselection_eligible','reselection_ready','conflict_count','confirmation_count','semantic_distance','semantic_age','target_id','reason']
  _slot_types = ['std_msgs/Header','uint8','string','uint8','string','bool','bool','bool','bool','bool','bool','uint32','uint32','float64','float64','int32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,fusion_state,fusion_state_text,semantic_evidence,semantic_evidence_text,camera_projection_valid,predicted_in_fov,yolo_target_present,yolo_lidar_component_valid,automatic_reselection_eligible,reselection_ready,conflict_count,confirmation_count,semantic_distance,semantic_age,target_id,reason

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FusionStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.fusion_state is None:
        self.fusion_state = 0
      if self.fusion_state_text is None:
        self.fusion_state_text = ''
      if self.semantic_evidence is None:
        self.semantic_evidence = 0
      if self.semantic_evidence_text is None:
        self.semantic_evidence_text = ''
      if self.camera_projection_valid is None:
        self.camera_projection_valid = False
      if self.predicted_in_fov is None:
        self.predicted_in_fov = False
      if self.yolo_target_present is None:
        self.yolo_target_present = False
      if self.yolo_lidar_component_valid is None:
        self.yolo_lidar_component_valid = False
      if self.automatic_reselection_eligible is None:
        self.automatic_reselection_eligible = False
      if self.reselection_ready is None:
        self.reselection_ready = False
      if self.conflict_count is None:
        self.conflict_count = 0
      if self.confirmation_count is None:
        self.confirmation_count = 0
      if self.semantic_distance is None:
        self.semantic_distance = 0.
      if self.semantic_age is None:
        self.semantic_age = 0.
      if self.target_id is None:
        self.target_id = 0
      if self.reason is None:
        self.reason = ''
    else:
      self.header = std_msgs.msg.Header()
      self.fusion_state = 0
      self.fusion_state_text = ''
      self.semantic_evidence = 0
      self.semantic_evidence_text = ''
      self.camera_projection_valid = False
      self.predicted_in_fov = False
      self.yolo_target_present = False
      self.yolo_lidar_component_valid = False
      self.automatic_reselection_eligible = False
      self.reselection_ready = False
      self.conflict_count = 0
      self.confirmation_count = 0
      self.semantic_distance = 0.
      self.semantic_age = 0.
      self.target_id = 0
      self.reason = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.fusion_state
      buff.write(_get_struct_B().pack(_x))
      _x = self.fusion_state_text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.semantic_evidence
      buff.write(_get_struct_B().pack(_x))
      _x = self.semantic_evidence_text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6B2I2di().pack(_x.camera_projection_valid, _x.predicted_in_fov, _x.yolo_target_present, _x.yolo_lidar_component_valid, _x.automatic_reselection_eligible, _x.reselection_ready, _x.conflict_count, _x.confirmation_count, _x.semantic_distance, _x.semantic_age, _x.target_id))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.fusion_state,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.fusion_state_text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.fusion_state_text = str[start:end]
      start = end
      end += 1
      (self.semantic_evidence,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.semantic_evidence_text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.semantic_evidence_text = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.camera_projection_valid, _x.predicted_in_fov, _x.yolo_target_present, _x.yolo_lidar_component_valid, _x.automatic_reselection_eligible, _x.reselection_ready, _x.conflict_count, _x.confirmation_count, _x.semantic_distance, _x.semantic_age, _x.target_id,) = _get_struct_6B2I2di().unpack(str[start:end])
      self.camera_projection_valid = bool(self.camera_projection_valid)
      self.predicted_in_fov = bool(self.predicted_in_fov)
      self.yolo_target_present = bool(self.yolo_target_present)
      self.yolo_lidar_component_valid = bool(self.yolo_lidar_component_valid)
      self.automatic_reselection_eligible = bool(self.automatic_reselection_eligible)
      self.reselection_ready = bool(self.reselection_ready)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.fusion_state
      buff.write(_get_struct_B().pack(_x))
      _x = self.fusion_state_text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.semantic_evidence
      buff.write(_get_struct_B().pack(_x))
      _x = self.semantic_evidence_text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6B2I2di().pack(_x.camera_projection_valid, _x.predicted_in_fov, _x.yolo_target_present, _x.yolo_lidar_component_valid, _x.automatic_reselection_eligible, _x.reselection_ready, _x.conflict_count, _x.confirmation_count, _x.semantic_distance, _x.semantic_age, _x.target_id))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.fusion_state,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.fusion_state_text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.fusion_state_text = str[start:end]
      start = end
      end += 1
      (self.semantic_evidence,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.semantic_evidence_text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.semantic_evidence_text = str[start:end]
      _x = self
      start = end
      end += 34
      (_x.camera_projection_valid, _x.predicted_in_fov, _x.yolo_target_present, _x.yolo_lidar_component_valid, _x.automatic_reselection_eligible, _x.reselection_ready, _x.conflict_count, _x.confirmation_count, _x.semantic_distance, _x.semantic_age, _x.target_id,) = _get_struct_6B2I2di().unpack(str[start:end])
      self.camera_projection_valid = bool(self.camera_projection_valid)
      self.predicted_in_fov = bool(self.predicted_in_fov)
      self.yolo_target_present = bool(self.yolo_target_present)
      self.yolo_lidar_component_valid = bool(self.yolo_lidar_component_valid)
      self.automatic_reselection_eligible = bool(self.automatic_reselection_eligible)
      self.reselection_ready = bool(self.reselection_ready)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_6B2I2di = None
def _get_struct_6B2I2di():
    global _struct_6B2I2di
    if _struct_6B2I2di is None:
        _struct_6B2I2di = struct.Struct("<6B2I2di")
    return _struct_6B2I2di
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
