# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from quadrotor_msgs/InspectionPointSet.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import quadrotor_msgs.msg
import std_msgs.msg

class InspectionPointSet(genpy.Message):
  _md5sum = "6ad14709e12727657e69b53b65581176"
  _type = "quadrotor_msgs/InspectionPointSet"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """InspectionPoint Point_set
================================================================================
MSG: quadrotor_msgs/InspectionPoint
std_msgs/Header                 header
uint64 seq
#attribute of the inspection point
bool                            IsInspectionPoint
geometry_msgs/Point             point                           #航点
bool                            free_nav                        #自由导航
bool                            ENABLE_YAW                      #使能航点yaw
float64                         point_yaw                       #航点yaw
float64                         stop_duration                   #航点处的停留时间
uint16[]                        ACTIONS                         #航点处需要执行的动作
geometry_msgs/Point             point_vel                       #用户指定的航点的速度默认且必须为0，为了确保轨迹平直而插入的点可以不为0
bool                            FORCEGOAL                       #用户给的强制点，接收到该点时可以在不是waittarget状态下直接进行规划    

#attribute of the inspection line
float64                         line_vel                        #航线上的速度 发布前需要提前确认是否与point vel冲突
bool                            ENABLE_LINE_AVOIDANCE           #是否沿线避障，若不避障则遇到障碍物急停，若避障则遇到障碍物后急停然后择机避障
float64                         avoidance_radius                #沿着航线上的避障半径

                         




================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['Point_set']
  _slot_types = ['quadrotor_msgs/InspectionPoint']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Point_set

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(InspectionPointSet, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Point_set is None:
        self.Point_set = quadrotor_msgs.msg.InspectionPoint()
    else:
      self.Point_set = quadrotor_msgs.msg.InspectionPoint()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.Point_set.header.seq, _x.Point_set.header.stamp.secs, _x.Point_set.header.stamp.nsecs))
      _x = self.Point_set.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_QB3d2B2d().pack(_x.Point_set.seq, _x.Point_set.IsInspectionPoint, _x.Point_set.point.x, _x.Point_set.point.y, _x.Point_set.point.z, _x.Point_set.free_nav, _x.Point_set.ENABLE_YAW, _x.Point_set.point_yaw, _x.Point_set.stop_duration))
      length = len(self.Point_set.ACTIONS)
      buff.write(_struct_I.pack(length))
      pattern = '<%sH'%length
      buff.write(struct.Struct(pattern).pack(*self.Point_set.ACTIONS))
      _x = self
      buff.write(_get_struct_3dBdBd().pack(_x.Point_set.point_vel.x, _x.Point_set.point_vel.y, _x.Point_set.point_vel.z, _x.Point_set.FORCEGOAL, _x.Point_set.line_vel, _x.Point_set.ENABLE_LINE_AVOIDANCE, _x.Point_set.avoidance_radius))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Point_set is None:
        self.Point_set = quadrotor_msgs.msg.InspectionPoint()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.Point_set.header.seq, _x.Point_set.header.stamp.secs, _x.Point_set.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Point_set.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Point_set.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 51
      (_x.Point_set.seq, _x.Point_set.IsInspectionPoint, _x.Point_set.point.x, _x.Point_set.point.y, _x.Point_set.point.z, _x.Point_set.free_nav, _x.Point_set.ENABLE_YAW, _x.Point_set.point_yaw, _x.Point_set.stop_duration,) = _get_struct_QB3d2B2d().unpack(str[start:end])
      self.Point_set.IsInspectionPoint = bool(self.Point_set.IsInspectionPoint)
      self.Point_set.free_nav = bool(self.Point_set.free_nav)
      self.Point_set.ENABLE_YAW = bool(self.Point_set.ENABLE_YAW)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sH'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.Point_set.ACTIONS = s.unpack(str[start:end])
      _x = self
      start = end
      end += 42
      (_x.Point_set.point_vel.x, _x.Point_set.point_vel.y, _x.Point_set.point_vel.z, _x.Point_set.FORCEGOAL, _x.Point_set.line_vel, _x.Point_set.ENABLE_LINE_AVOIDANCE, _x.Point_set.avoidance_radius,) = _get_struct_3dBdBd().unpack(str[start:end])
      self.Point_set.FORCEGOAL = bool(self.Point_set.FORCEGOAL)
      self.Point_set.ENABLE_LINE_AVOIDANCE = bool(self.Point_set.ENABLE_LINE_AVOIDANCE)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.Point_set.header.seq, _x.Point_set.header.stamp.secs, _x.Point_set.header.stamp.nsecs))
      _x = self.Point_set.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_QB3d2B2d().pack(_x.Point_set.seq, _x.Point_set.IsInspectionPoint, _x.Point_set.point.x, _x.Point_set.point.y, _x.Point_set.point.z, _x.Point_set.free_nav, _x.Point_set.ENABLE_YAW, _x.Point_set.point_yaw, _x.Point_set.stop_duration))
      length = len(self.Point_set.ACTIONS)
      buff.write(_struct_I.pack(length))
      pattern = '<%sH'%length
      buff.write(self.Point_set.ACTIONS.tostring())
      _x = self
      buff.write(_get_struct_3dBdBd().pack(_x.Point_set.point_vel.x, _x.Point_set.point_vel.y, _x.Point_set.point_vel.z, _x.Point_set.FORCEGOAL, _x.Point_set.line_vel, _x.Point_set.ENABLE_LINE_AVOIDANCE, _x.Point_set.avoidance_radius))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Point_set is None:
        self.Point_set = quadrotor_msgs.msg.InspectionPoint()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.Point_set.header.seq, _x.Point_set.header.stamp.secs, _x.Point_set.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Point_set.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Point_set.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 51
      (_x.Point_set.seq, _x.Point_set.IsInspectionPoint, _x.Point_set.point.x, _x.Point_set.point.y, _x.Point_set.point.z, _x.Point_set.free_nav, _x.Point_set.ENABLE_YAW, _x.Point_set.point_yaw, _x.Point_set.stop_duration,) = _get_struct_QB3d2B2d().unpack(str[start:end])
      self.Point_set.IsInspectionPoint = bool(self.Point_set.IsInspectionPoint)
      self.Point_set.free_nav = bool(self.Point_set.free_nav)
      self.Point_set.ENABLE_YAW = bool(self.Point_set.ENABLE_YAW)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sH'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.Point_set.ACTIONS = numpy.frombuffer(str[start:end], dtype=numpy.uint16, count=length)
      _x = self
      start = end
      end += 42
      (_x.Point_set.point_vel.x, _x.Point_set.point_vel.y, _x.Point_set.point_vel.z, _x.Point_set.FORCEGOAL, _x.Point_set.line_vel, _x.Point_set.ENABLE_LINE_AVOIDANCE, _x.Point_set.avoidance_radius,) = _get_struct_3dBdBd().unpack(str[start:end])
      self.Point_set.FORCEGOAL = bool(self.Point_set.FORCEGOAL)
      self.Point_set.ENABLE_LINE_AVOIDANCE = bool(self.Point_set.ENABLE_LINE_AVOIDANCE)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3dBdBd = None
def _get_struct_3dBdBd():
    global _struct_3dBdBd
    if _struct_3dBdBd is None:
        _struct_3dBdBd = struct.Struct("<3dBdBd")
    return _struct_3dBdBd
_struct_QB3d2B2d = None
def _get_struct_QB3d2B2d():
    global _struct_QB3d2B2d
    if _struct_QB3d2B2d is None:
        _struct_QB3d2B2d = struct.Struct("<QB3d2B2d")
    return _struct_QB3d2B2d
