# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from quadrotor_msgs/TakeoffLand.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TakeoffLand(genpy.Message):
  _md5sum = "9c4ee059521d491616617187915bab8e"
  _type = "quadrotor_msgs/TakeoffLand"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 seq
uint8 TAKEOFF = 1
uint8 LAND = 2
uint8 takeoff_land_cmd
float64 takeoff_hight"""
  # Pseudo-constants
  TAKEOFF = 1
  LAND = 2

  __slots__ = ['seq','takeoff_land_cmd','takeoff_hight']
  _slot_types = ['uint64','uint8','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       seq,takeoff_land_cmd,takeoff_hight

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TakeoffLand, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.seq is None:
        self.seq = 0
      if self.takeoff_land_cmd is None:
        self.takeoff_land_cmd = 0
      if self.takeoff_hight is None:
        self.takeoff_hight = 0.
    else:
      self.seq = 0
      self.takeoff_land_cmd = 0
      self.takeoff_hight = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_QBd().pack(_x.seq, _x.takeoff_land_cmd, _x.takeoff_hight))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.seq, _x.takeoff_land_cmd, _x.takeoff_hight,) = _get_struct_QBd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_QBd().pack(_x.seq, _x.takeoff_land_cmd, _x.takeoff_hight))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.seq, _x.takeoff_land_cmd, _x.takeoff_hight,) = _get_struct_QBd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_QBd = None
def _get_struct_QBd():
    global _struct_QBd
    if _struct_QBd is None:
        _struct_QBd = struct.Struct("<QBd")
    return _struct_QBd
