# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from general_planner/ExplorationTrajectory.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import traj_utils.msg

class ExplorationTrajectory(genpy.Message):
  _md5sum = "78945e84c09526734c24f8463f3e835a"
  _type = "general_planner/ExplorationTrajectory"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 task_epoch
string task_id
traj_utils/PolyTraj position
traj_utils/PolyTraj yaw

================================================================================
MSG: traj_utils/PolyTraj
int16 drone_id
int32 traj_id
time start_time

uint8 order
float32[] coef_x
float32[] coef_y
float32[] coef_z
float32[] duration
"""
  __slots__ = ['task_epoch','task_id','position','yaw']
  _slot_types = ['uint64','string','traj_utils/PolyTraj','traj_utils/PolyTraj']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       task_epoch,task_id,position,yaw

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ExplorationTrajectory, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.task_epoch is None:
        self.task_epoch = 0
      if self.task_id is None:
        self.task_id = ''
      if self.position is None:
        self.position = traj_utils.msg.PolyTraj()
      if self.yaw is None:
        self.yaw = traj_utils.msg.PolyTraj()
    else:
      self.task_epoch = 0
      self.task_id = ''
      self.position = traj_utils.msg.PolyTraj()
      self.yaw = traj_utils.msg.PolyTraj()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.task_epoch
      buff.write(_get_struct_Q().pack(_x))
      _x = self.task_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_hi2IB().pack(_x.position.drone_id, _x.position.traj_id, _x.position.start_time.secs, _x.position.start_time.nsecs, _x.position.order))
      length = len(self.position.coef_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.position.coef_x))
      length = len(self.position.coef_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.position.coef_y))
      length = len(self.position.coef_z)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.position.coef_z))
      length = len(self.position.duration)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.position.duration))
      _x = self
      buff.write(_get_struct_hi2IB().pack(_x.yaw.drone_id, _x.yaw.traj_id, _x.yaw.start_time.secs, _x.yaw.start_time.nsecs, _x.yaw.order))
      length = len(self.yaw.coef_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.yaw.coef_x))
      length = len(self.yaw.coef_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.yaw.coef_y))
      length = len(self.yaw.coef_z)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.yaw.coef_z))
      length = len(self.yaw.duration)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.yaw.duration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = traj_utils.msg.PolyTraj()
      if self.yaw is None:
        self.yaw = traj_utils.msg.PolyTraj()
      end = 0
      start = end
      end += 8
      (self.task_epoch,) = _get_struct_Q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.task_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.task_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.position.drone_id, _x.position.traj_id, _x.position.start_time.secs, _x.position.start_time.nsecs, _x.position.order,) = _get_struct_hi2IB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.position.coef_x = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.position.coef_y = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.position.coef_z = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.position.duration = s.unpack(str[start:end])
      _x = self
      start = end
      end += 15
      (_x.yaw.drone_id, _x.yaw.traj_id, _x.yaw.start_time.secs, _x.yaw.start_time.nsecs, _x.yaw.order,) = _get_struct_hi2IB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.yaw.coef_x = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.yaw.coef_y = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.yaw.coef_z = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.yaw.duration = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.task_epoch
      buff.write(_get_struct_Q().pack(_x))
      _x = self.task_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_hi2IB().pack(_x.position.drone_id, _x.position.traj_id, _x.position.start_time.secs, _x.position.start_time.nsecs, _x.position.order))
      length = len(self.position.coef_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.position.coef_x.tostring())
      length = len(self.position.coef_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.position.coef_y.tostring())
      length = len(self.position.coef_z)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.position.coef_z.tostring())
      length = len(self.position.duration)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.position.duration.tostring())
      _x = self
      buff.write(_get_struct_hi2IB().pack(_x.yaw.drone_id, _x.yaw.traj_id, _x.yaw.start_time.secs, _x.yaw.start_time.nsecs, _x.yaw.order))
      length = len(self.yaw.coef_x)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.yaw.coef_x.tostring())
      length = len(self.yaw.coef_y)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.yaw.coef_y.tostring())
      length = len(self.yaw.coef_z)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.yaw.coef_z.tostring())
      length = len(self.yaw.duration)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.yaw.duration.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = traj_utils.msg.PolyTraj()
      if self.yaw is None:
        self.yaw = traj_utils.msg.PolyTraj()
      end = 0
      start = end
      end += 8
      (self.task_epoch,) = _get_struct_Q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.task_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.task_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.position.drone_id, _x.position.traj_id, _x.position.start_time.secs, _x.position.start_time.nsecs, _x.position.order,) = _get_struct_hi2IB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.position.coef_x = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.position.coef_y = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.position.coef_z = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.position.duration = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 15
      (_x.yaw.drone_id, _x.yaw.traj_id, _x.yaw.start_time.secs, _x.yaw.start_time.nsecs, _x.yaw.order,) = _get_struct_hi2IB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.yaw.coef_x = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.yaw.coef_y = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.yaw.coef_z = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.yaw.duration = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Q = None
def _get_struct_Q():
    global _struct_Q
    if _struct_Q is None:
        _struct_Q = struct.Struct("<Q")
    return _struct_Q
_struct_hi2IB = None
def _get_struct_hi2IB():
    global _struct_hi2IB
    if _struct_hi2IB is None:
        _struct_hi2IB = struct.Struct("<hi2IB")
    return _struct_hi2IB
