# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from general_planner/FrontierCluster.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class FrontierCluster(genpy.Message):
  _md5sum = "937c5aa1a798a8e0d9ffb1c40d458e0b"
  _type = "general_planner/FrontierCluster"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Semantic frontier cluster exposed to upper layers / release consumers.
# This is not a voxel-center cloud; it mirrors ClusterInfo used by exploration.

int32 id

geometry_msgs/Point center
geometry_msgs/Vector3 normal
geometry_msgs/Pose best_viewpoint
geometry_msgs/Point box_min
geometry_msgs/Point box_max

uint8 state
bool is_reachable
bool is_dormant
bool is_new_cluster

float32 visible_gain
float32 score
float32 distance

uint8 STATE_ACTIVE=0
uint8 STATE_SELECTED=1
uint8 STATE_PENDING_RETRY=2
uint8 STATE_SUSPENDED=3
uint8 STATE_DEFERRED_BRANCH=4
uint8 STATE_VISITED=5
uint8 STATE_BLACKLISTED=6

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  # Pseudo-constants
  STATE_ACTIVE = 0
  STATE_SELECTED = 1
  STATE_PENDING_RETRY = 2
  STATE_SUSPENDED = 3
  STATE_DEFERRED_BRANCH = 4
  STATE_VISITED = 5
  STATE_BLACKLISTED = 6

  __slots__ = ['id','center','normal','best_viewpoint','box_min','box_max','state','is_reachable','is_dormant','is_new_cluster','visible_gain','score','distance']
  _slot_types = ['int32','geometry_msgs/Point','geometry_msgs/Vector3','geometry_msgs/Pose','geometry_msgs/Point','geometry_msgs/Point','uint8','bool','bool','bool','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,center,normal,best_viewpoint,box_min,box_max,state,is_reachable,is_dormant,is_new_cluster,visible_gain,score,distance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FrontierCluster, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.center is None:
        self.center = geometry_msgs.msg.Point()
      if self.normal is None:
        self.normal = geometry_msgs.msg.Vector3()
      if self.best_viewpoint is None:
        self.best_viewpoint = geometry_msgs.msg.Pose()
      if self.box_min is None:
        self.box_min = geometry_msgs.msg.Point()
      if self.box_max is None:
        self.box_max = geometry_msgs.msg.Point()
      if self.state is None:
        self.state = 0
      if self.is_reachable is None:
        self.is_reachable = False
      if self.is_dormant is None:
        self.is_dormant = False
      if self.is_new_cluster is None:
        self.is_new_cluster = False
      if self.visible_gain is None:
        self.visible_gain = 0.
      if self.score is None:
        self.score = 0.
      if self.distance is None:
        self.distance = 0.
    else:
      self.id = 0
      self.center = geometry_msgs.msg.Point()
      self.normal = geometry_msgs.msg.Vector3()
      self.best_viewpoint = geometry_msgs.msg.Pose()
      self.box_min = geometry_msgs.msg.Point()
      self.box_max = geometry_msgs.msg.Point()
      self.state = 0
      self.is_reachable = False
      self.is_dormant = False
      self.is_new_cluster = False
      self.visible_gain = 0.
      self.score = 0.
      self.distance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i19d4B3f().pack(_x.id, _x.center.x, _x.center.y, _x.center.z, _x.normal.x, _x.normal.y, _x.normal.z, _x.best_viewpoint.position.x, _x.best_viewpoint.position.y, _x.best_viewpoint.position.z, _x.best_viewpoint.orientation.x, _x.best_viewpoint.orientation.y, _x.best_viewpoint.orientation.z, _x.best_viewpoint.orientation.w, _x.box_min.x, _x.box_min.y, _x.box_min.z, _x.box_max.x, _x.box_max.y, _x.box_max.z, _x.state, _x.is_reachable, _x.is_dormant, _x.is_new_cluster, _x.visible_gain, _x.score, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.center is None:
        self.center = geometry_msgs.msg.Point()
      if self.normal is None:
        self.normal = geometry_msgs.msg.Vector3()
      if self.best_viewpoint is None:
        self.best_viewpoint = geometry_msgs.msg.Pose()
      if self.box_min is None:
        self.box_min = geometry_msgs.msg.Point()
      if self.box_max is None:
        self.box_max = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 172
      (_x.id, _x.center.x, _x.center.y, _x.center.z, _x.normal.x, _x.normal.y, _x.normal.z, _x.best_viewpoint.position.x, _x.best_viewpoint.position.y, _x.best_viewpoint.position.z, _x.best_viewpoint.orientation.x, _x.best_viewpoint.orientation.y, _x.best_viewpoint.orientation.z, _x.best_viewpoint.orientation.w, _x.box_min.x, _x.box_min.y, _x.box_min.z, _x.box_max.x, _x.box_max.y, _x.box_max.z, _x.state, _x.is_reachable, _x.is_dormant, _x.is_new_cluster, _x.visible_gain, _x.score, _x.distance,) = _get_struct_i19d4B3f().unpack(str[start:end])
      self.is_reachable = bool(self.is_reachable)
      self.is_dormant = bool(self.is_dormant)
      self.is_new_cluster = bool(self.is_new_cluster)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i19d4B3f().pack(_x.id, _x.center.x, _x.center.y, _x.center.z, _x.normal.x, _x.normal.y, _x.normal.z, _x.best_viewpoint.position.x, _x.best_viewpoint.position.y, _x.best_viewpoint.position.z, _x.best_viewpoint.orientation.x, _x.best_viewpoint.orientation.y, _x.best_viewpoint.orientation.z, _x.best_viewpoint.orientation.w, _x.box_min.x, _x.box_min.y, _x.box_min.z, _x.box_max.x, _x.box_max.y, _x.box_max.z, _x.state, _x.is_reachable, _x.is_dormant, _x.is_new_cluster, _x.visible_gain, _x.score, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.center is None:
        self.center = geometry_msgs.msg.Point()
      if self.normal is None:
        self.normal = geometry_msgs.msg.Vector3()
      if self.best_viewpoint is None:
        self.best_viewpoint = geometry_msgs.msg.Pose()
      if self.box_min is None:
        self.box_min = geometry_msgs.msg.Point()
      if self.box_max is None:
        self.box_max = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 172
      (_x.id, _x.center.x, _x.center.y, _x.center.z, _x.normal.x, _x.normal.y, _x.normal.z, _x.best_viewpoint.position.x, _x.best_viewpoint.position.y, _x.best_viewpoint.position.z, _x.best_viewpoint.orientation.x, _x.best_viewpoint.orientation.y, _x.best_viewpoint.orientation.z, _x.best_viewpoint.orientation.w, _x.box_min.x, _x.box_min.y, _x.box_min.z, _x.box_max.x, _x.box_max.y, _x.box_max.z, _x.state, _x.is_reachable, _x.is_dormant, _x.is_new_cluster, _x.visible_gain, _x.score, _x.distance,) = _get_struct_i19d4B3f().unpack(str[start:end])
      self.is_reachable = bool(self.is_reachable)
      self.is_dormant = bool(self.is_dormant)
      self.is_new_cluster = bool(self.is_new_cluster)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i19d4B3f = None
def _get_struct_i19d4B3f():
    global _struct_i19d4B3f
    if _struct_i19d4B3f is None:
        _struct_i19d4B3f = struct.Struct("<i19d4B3f")
    return _struct_i19d4B3f
