# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from general_planner/PlannerPositionCommand.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import quadrotor_msgs.msg
import std_msgs.msg

class PlannerPositionCommand(genpy.Message):
  _md5sum = "06c1da0d31974e4b608776eaa913c7e8"
  _type = "general_planner/PlannerPositionCommand"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 task_epoch
string task_id
quadrotor_msgs/PositionCommand command

================================================================================
MSG: quadrotor_msgs/PositionCommand
Header header
geometry_msgs/Point position
geometry_msgs/Vector3 velocity
geometry_msgs/Vector3 acceleration
geometry_msgs/Vector3 jerk
geometry_msgs/Vector3 angular_velocity
geometry_msgs/Vector3 attitude
geometry_msgs/Vector3 thrust
float64 yaw
float64 yaw_dot
float64 vel_norm
float64 acc_norm


float64[3] kx
float64[3] kv
uint32 trajectory_id
uint8 TRAJECTORY_STATUS_EMPTY = 0
uint8 TRAJECTORY_STATUS_EMER = 2
uint8 TRAJECTORY_STATUS_READY = 1
uint8 TRAJECTORY_STATUS_COMPLETED = 3
uint8 TRAJECTROY_STATUS_ABORT = 4
uint8 TRAJECTORY_STATUS_ILLEGAL_START = 5
uint8 TRAJECTORY_STATUS_ILLEGAL_FINAL = 6
uint8 TRAJECTORY_STATUS_IMPOSSIBLE = 7
uint32 ACTION_STOP                 =   8
# Its ID number will start from 1, allowing you comparing it with 0.
uint8 trajectory_flag

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['task_epoch','task_id','command']
  _slot_types = ['uint64','string','quadrotor_msgs/PositionCommand']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       task_epoch,task_id,command

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlannerPositionCommand, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.task_epoch is None:
        self.task_epoch = 0
      if self.task_id is None:
        self.task_id = ''
      if self.command is None:
        self.command = quadrotor_msgs.msg.PositionCommand()
    else:
      self.task_epoch = 0
      self.task_id = ''
      self.command = quadrotor_msgs.msg.PositionCommand()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.task_epoch
      buff.write(_get_struct_Q().pack(_x))
      _x = self.task_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.command.header.seq, _x.command.header.stamp.secs, _x.command.header.stamp.nsecs))
      _x = self.command.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_25d().pack(_x.command.position.x, _x.command.position.y, _x.command.position.z, _x.command.velocity.x, _x.command.velocity.y, _x.command.velocity.z, _x.command.acceleration.x, _x.command.acceleration.y, _x.command.acceleration.z, _x.command.jerk.x, _x.command.jerk.y, _x.command.jerk.z, _x.command.angular_velocity.x, _x.command.angular_velocity.y, _x.command.angular_velocity.z, _x.command.attitude.x, _x.command.attitude.y, _x.command.attitude.z, _x.command.thrust.x, _x.command.thrust.y, _x.command.thrust.z, _x.command.yaw, _x.command.yaw_dot, _x.command.vel_norm, _x.command.acc_norm))
      buff.write(_get_struct_3d().pack(*self.command.kx))
      buff.write(_get_struct_3d().pack(*self.command.kv))
      _x = self
      buff.write(_get_struct_IB().pack(_x.command.trajectory_id, _x.command.trajectory_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.command is None:
        self.command = quadrotor_msgs.msg.PositionCommand()
      end = 0
      start = end
      end += 8
      (self.task_epoch,) = _get_struct_Q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.task_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.task_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.command.header.seq, _x.command.header.stamp.secs, _x.command.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.command.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.command.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 200
      (_x.command.position.x, _x.command.position.y, _x.command.position.z, _x.command.velocity.x, _x.command.velocity.y, _x.command.velocity.z, _x.command.acceleration.x, _x.command.acceleration.y, _x.command.acceleration.z, _x.command.jerk.x, _x.command.jerk.y, _x.command.jerk.z, _x.command.angular_velocity.x, _x.command.angular_velocity.y, _x.command.angular_velocity.z, _x.command.attitude.x, _x.command.attitude.y, _x.command.attitude.z, _x.command.thrust.x, _x.command.thrust.y, _x.command.thrust.z, _x.command.yaw, _x.command.yaw_dot, _x.command.vel_norm, _x.command.acc_norm,) = _get_struct_25d().unpack(str[start:end])
      start = end
      end += 24
      self.command.kx = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 24
      self.command.kv = _get_struct_3d().unpack(str[start:end])
      _x = self
      start = end
      end += 5
      (_x.command.trajectory_id, _x.command.trajectory_flag,) = _get_struct_IB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.task_epoch
      buff.write(_get_struct_Q().pack(_x))
      _x = self.task_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.command.header.seq, _x.command.header.stamp.secs, _x.command.header.stamp.nsecs))
      _x = self.command.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_25d().pack(_x.command.position.x, _x.command.position.y, _x.command.position.z, _x.command.velocity.x, _x.command.velocity.y, _x.command.velocity.z, _x.command.acceleration.x, _x.command.acceleration.y, _x.command.acceleration.z, _x.command.jerk.x, _x.command.jerk.y, _x.command.jerk.z, _x.command.angular_velocity.x, _x.command.angular_velocity.y, _x.command.angular_velocity.z, _x.command.attitude.x, _x.command.attitude.y, _x.command.attitude.z, _x.command.thrust.x, _x.command.thrust.y, _x.command.thrust.z, _x.command.yaw, _x.command.yaw_dot, _x.command.vel_norm, _x.command.acc_norm))
      buff.write(self.command.kx.tostring())
      buff.write(self.command.kv.tostring())
      _x = self
      buff.write(_get_struct_IB().pack(_x.command.trajectory_id, _x.command.trajectory_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.command is None:
        self.command = quadrotor_msgs.msg.PositionCommand()
      end = 0
      start = end
      end += 8
      (self.task_epoch,) = _get_struct_Q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.task_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.task_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.command.header.seq, _x.command.header.stamp.secs, _x.command.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.command.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.command.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 200
      (_x.command.position.x, _x.command.position.y, _x.command.position.z, _x.command.velocity.x, _x.command.velocity.y, _x.command.velocity.z, _x.command.acceleration.x, _x.command.acceleration.y, _x.command.acceleration.z, _x.command.jerk.x, _x.command.jerk.y, _x.command.jerk.z, _x.command.angular_velocity.x, _x.command.angular_velocity.y, _x.command.angular_velocity.z, _x.command.attitude.x, _x.command.attitude.y, _x.command.attitude.z, _x.command.thrust.x, _x.command.thrust.y, _x.command.thrust.z, _x.command.yaw, _x.command.yaw_dot, _x.command.vel_norm, _x.command.acc_norm,) = _get_struct_25d().unpack(str[start:end])
      start = end
      end += 24
      self.command.kx = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      start = end
      end += 24
      self.command.kv = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=3)
      _x = self
      start = end
      end += 5
      (_x.command.trajectory_id, _x.command.trajectory_flag,) = _get_struct_IB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_25d = None
def _get_struct_25d():
    global _struct_25d
    if _struct_25d is None:
        _struct_25d = struct.Struct("<25d")
    return _struct_25d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_IB = None
def _get_struct_IB():
    global _struct_IB
    if _struct_IB is None:
        _struct_IB = struct.Struct("<IB")
    return _struct_IB
_struct_Q = None
def _get_struct_Q():
    global _struct_Q
    if _struct_Q is None:
        _struct_Q = struct.Struct("<Q")
    return _struct_Q
