# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from general_planner/PlannerStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class PlannerStatus(genpy.Message):
  _md5sum = "923c9b743d992dd11a5936af5395d6e7"
  _type = "general_planner/PlannerStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
uint64 transition_id
uint64 task_epoch
uint64 world_epoch
uint64 map_revision
uint64 topo_revision
uint64 accepted_request_id

string task_id
uint8 active_mode
uint8 requested_mode
uint8 phase
uint16 mode_state
uint8 task_result

# Human-readable mirrors of the enums above for rostopic echo / upper layers.
string active_mode_str
string requested_mode_str
string phase_str
string mode_state_str
string command_owner_str
string task_result_str

bool stable_hover
bool ready_for_new_task
bool odom_valid
bool map_ready
bool topology_ready
uint8 command_owner
float32 speed_mps
float32 yaw_rate_rps
string reason

uint8 MODE_HOLD=0
uint8 MODE_STATE2STATE=1
uint8 MODE_EXPLORATION=2
uint8 MODE_EMERGENCY_STOP=3

uint8 PHASE_BOOT=0
uint8 PHASE_WAITING_INPUT=1
uint8 PHASE_PLANNING=2
uint8 PHASE_EXECUTING=3
uint8 PHASE_BRAKING=4
uint8 PHASE_HOLD_VERIFY=5
uint8 PHASE_STABLE_HOLD=6
uint8 PHASE_FAILED=7
uint8 PHASE_EMERGENCY=8

uint8 RESULT_NONE=0
uint8 RESULT_SUCCEEDED=1
uint8 RESULT_FAILED=2
uint8 RESULT_CANCELED=3

uint8 OWNER_HOLD=0
uint8 OWNER_STATE2STATE=1
uint8 OWNER_EXPLORATION=2

uint16 MODE_STATE_UNKNOWN=0
uint16 MODE_STATE_S2S_WAIT_GOAL=1
uint16 MODE_STATE_S2S_GENERATE_TRAJ=2
uint16 MODE_STATE_S2S_FOLLOW_TRAJ=3
uint16 MODE_STATE_S2S_YAWING=4
uint16 MODE_STATE_S2S_EMER_STOP=5
uint16 MODE_STATE_EXP_INIT=10
uint16 MODE_STATE_EXP_WAIT_TRIGGER=11
uint16 MODE_STATE_EXP_PLAN_TRAJ=12
uint16 MODE_STATE_EXP_EXEC_TRAJ=13
uint16 MODE_STATE_EXP_REORIENT=14
uint16 MODE_STATE_EXP_CAUTION=15
uint16 MODE_STATE_EXP_PAUSING=16
uint16 MODE_STATE_EXP_PAUSED=17
uint16 MODE_STATE_EXP_FINISH=18
uint16 MODE_STATE_HOLD_IDLE=20

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  # Pseudo-constants
  MODE_HOLD = 0
  MODE_STATE2STATE = 1
  MODE_EXPLORATION = 2
  MODE_EMERGENCY_STOP = 3
  PHASE_BOOT = 0
  PHASE_WAITING_INPUT = 1
  PHASE_PLANNING = 2
  PHASE_EXECUTING = 3
  PHASE_BRAKING = 4
  PHASE_HOLD_VERIFY = 5
  PHASE_STABLE_HOLD = 6
  PHASE_FAILED = 7
  PHASE_EMERGENCY = 8
  RESULT_NONE = 0
  RESULT_SUCCEEDED = 1
  RESULT_FAILED = 2
  RESULT_CANCELED = 3
  OWNER_HOLD = 0
  OWNER_STATE2STATE = 1
  OWNER_EXPLORATION = 2
  MODE_STATE_UNKNOWN = 0
  MODE_STATE_S2S_WAIT_GOAL = 1
  MODE_STATE_S2S_GENERATE_TRAJ = 2
  MODE_STATE_S2S_FOLLOW_TRAJ = 3
  MODE_STATE_S2S_YAWING = 4
  MODE_STATE_S2S_EMER_STOP = 5
  MODE_STATE_EXP_INIT = 10
  MODE_STATE_EXP_WAIT_TRIGGER = 11
  MODE_STATE_EXP_PLAN_TRAJ = 12
  MODE_STATE_EXP_EXEC_TRAJ = 13
  MODE_STATE_EXP_REORIENT = 14
  MODE_STATE_EXP_CAUTION = 15
  MODE_STATE_EXP_PAUSING = 16
  MODE_STATE_EXP_PAUSED = 17
  MODE_STATE_EXP_FINISH = 18
  MODE_STATE_HOLD_IDLE = 20

  __slots__ = ['header','transition_id','task_epoch','world_epoch','map_revision','topo_revision','accepted_request_id','task_id','active_mode','requested_mode','phase','mode_state','task_result','active_mode_str','requested_mode_str','phase_str','mode_state_str','command_owner_str','task_result_str','stable_hover','ready_for_new_task','odom_valid','map_ready','topology_ready','command_owner','speed_mps','yaw_rate_rps','reason']
  _slot_types = ['std_msgs/Header','uint64','uint64','uint64','uint64','uint64','uint64','string','uint8','uint8','uint8','uint16','uint8','string','string','string','string','string','string','bool','bool','bool','bool','bool','uint8','float32','float32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,transition_id,task_epoch,world_epoch,map_revision,topo_revision,accepted_request_id,task_id,active_mode,requested_mode,phase,mode_state,task_result,active_mode_str,requested_mode_str,phase_str,mode_state_str,command_owner_str,task_result_str,stable_hover,ready_for_new_task,odom_valid,map_ready,topology_ready,command_owner,speed_mps,yaw_rate_rps,reason

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlannerStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.transition_id is None:
        self.transition_id = 0
      if self.task_epoch is None:
        self.task_epoch = 0
      if self.world_epoch is None:
        self.world_epoch = 0
      if self.map_revision is None:
        self.map_revision = 0
      if self.topo_revision is None:
        self.topo_revision = 0
      if self.accepted_request_id is None:
        self.accepted_request_id = 0
      if self.task_id is None:
        self.task_id = ''
      if self.active_mode is None:
        self.active_mode = 0
      if self.requested_mode is None:
        self.requested_mode = 0
      if self.phase is None:
        self.phase = 0
      if self.mode_state is None:
        self.mode_state = 0
      if self.task_result is None:
        self.task_result = 0
      if self.active_mode_str is None:
        self.active_mode_str = ''
      if self.requested_mode_str is None:
        self.requested_mode_str = ''
      if self.phase_str is None:
        self.phase_str = ''
      if self.mode_state_str is None:
        self.mode_state_str = ''
      if self.command_owner_str is None:
        self.command_owner_str = ''
      if self.task_result_str is None:
        self.task_result_str = ''
      if self.stable_hover is None:
        self.stable_hover = False
      if self.ready_for_new_task is None:
        self.ready_for_new_task = False
      if self.odom_valid is None:
        self.odom_valid = False
      if self.map_ready is None:
        self.map_ready = False
      if self.topology_ready is None:
        self.topology_ready = False
      if self.command_owner is None:
        self.command_owner = 0
      if self.speed_mps is None:
        self.speed_mps = 0.
      if self.yaw_rate_rps is None:
        self.yaw_rate_rps = 0.
      if self.reason is None:
        self.reason = ''
    else:
      self.header = std_msgs.msg.Header()
      self.transition_id = 0
      self.task_epoch = 0
      self.world_epoch = 0
      self.map_revision = 0
      self.topo_revision = 0
      self.accepted_request_id = 0
      self.task_id = ''
      self.active_mode = 0
      self.requested_mode = 0
      self.phase = 0
      self.mode_state = 0
      self.task_result = 0
      self.active_mode_str = ''
      self.requested_mode_str = ''
      self.phase_str = ''
      self.mode_state_str = ''
      self.command_owner_str = ''
      self.task_result_str = ''
      self.stable_hover = False
      self.ready_for_new_task = False
      self.odom_valid = False
      self.map_ready = False
      self.topology_ready = False
      self.command_owner = 0
      self.speed_mps = 0.
      self.yaw_rate_rps = 0.
      self.reason = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6Q().pack(_x.transition_id, _x.task_epoch, _x.world_epoch, _x.map_revision, _x.topo_revision, _x.accepted_request_id))
      _x = self.task_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3BHB().pack(_x.active_mode, _x.requested_mode, _x.phase, _x.mode_state, _x.task_result))
      _x = self.active_mode_str
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.requested_mode_str
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.phase_str
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.mode_state_str
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.command_owner_str
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.task_result_str
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6B2f().pack(_x.stable_hover, _x.ready_for_new_task, _x.odom_valid, _x.map_ready, _x.topology_ready, _x.command_owner, _x.speed_mps, _x.yaw_rate_rps))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.transition_id, _x.task_epoch, _x.world_epoch, _x.map_revision, _x.topo_revision, _x.accepted_request_id,) = _get_struct_6Q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.task_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.task_id = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.active_mode, _x.requested_mode, _x.phase, _x.mode_state, _x.task_result,) = _get_struct_3BHB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.active_mode_str = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.active_mode_str = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.requested_mode_str = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.requested_mode_str = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.phase_str = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.phase_str = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mode_state_str = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.mode_state_str = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.command_owner_str = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.command_owner_str = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.task_result_str = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.task_result_str = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.stable_hover, _x.ready_for_new_task, _x.odom_valid, _x.map_ready, _x.topology_ready, _x.command_owner, _x.speed_mps, _x.yaw_rate_rps,) = _get_struct_6B2f().unpack(str[start:end])
      self.stable_hover = bool(self.stable_hover)
      self.ready_for_new_task = bool(self.ready_for_new_task)
      self.odom_valid = bool(self.odom_valid)
      self.map_ready = bool(self.map_ready)
      self.topology_ready = bool(self.topology_ready)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6Q().pack(_x.transition_id, _x.task_epoch, _x.world_epoch, _x.map_revision, _x.topo_revision, _x.accepted_request_id))
      _x = self.task_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3BHB().pack(_x.active_mode, _x.requested_mode, _x.phase, _x.mode_state, _x.task_result))
      _x = self.active_mode_str
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.requested_mode_str
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.phase_str
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.mode_state_str
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.command_owner_str
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.task_result_str
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6B2f().pack(_x.stable_hover, _x.ready_for_new_task, _x.odom_valid, _x.map_ready, _x.topology_ready, _x.command_owner, _x.speed_mps, _x.yaw_rate_rps))
      _x = self.reason
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.transition_id, _x.task_epoch, _x.world_epoch, _x.map_revision, _x.topo_revision, _x.accepted_request_id,) = _get_struct_6Q().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.task_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.task_id = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.active_mode, _x.requested_mode, _x.phase, _x.mode_state, _x.task_result,) = _get_struct_3BHB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.active_mode_str = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.active_mode_str = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.requested_mode_str = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.requested_mode_str = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.phase_str = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.phase_str = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mode_state_str = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.mode_state_str = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.command_owner_str = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.command_owner_str = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.task_result_str = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.task_result_str = str[start:end]
      _x = self
      start = end
      end += 14
      (_x.stable_hover, _x.ready_for_new_task, _x.odom_valid, _x.map_ready, _x.topology_ready, _x.command_owner, _x.speed_mps, _x.yaw_rate_rps,) = _get_struct_6B2f().unpack(str[start:end])
      self.stable_hover = bool(self.stable_hover)
      self.ready_for_new_task = bool(self.ready_for_new_task)
      self.odom_valid = bool(self.odom_valid)
      self.map_ready = bool(self.map_ready)
      self.topology_ready = bool(self.topology_ready)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.reason = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.reason = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3BHB = None
def _get_struct_3BHB():
    global _struct_3BHB
    if _struct_3BHB is None:
        _struct_3BHB = struct.Struct("<3BHB")
    return _struct_3BHB
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_6B2f = None
def _get_struct_6B2f():
    global _struct_6B2f
    if _struct_6B2f is None:
        _struct_6B2f = struct.Struct("<6B2f")
    return _struct_6B2f
_struct_6Q = None
def _get_struct_6Q():
    global _struct_6Q
    if _struct_6Q is None:
        _struct_6Q = struct.Struct("<6Q")
    return _struct_6Q
