# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from general_planner/TopologyExpansionPoint.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class TopologyExpansionPoint(genpy.Message):
  _md5sum = "3a30150b5dfd7e2580c24f58d1a56aef"
  _type = "general_planner/TopologyExpansionPoint"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# A persistent global-topology node exposed as a frontier-equivalent point.
# `is_expandable` means that at least one selected portal face has no active
# topology edge to an adjacent region. It is a topology-growth candidate, not
# a guarantee that the corresponding map direction is traversable.

uint64 id
geometry_msgs/Point position
float32 clearance
uint32 degree
uint8 state
bool is_expandable
uint8 portal_mask
uint8 expansion_mask
uint64 node_revision
uint64 last_observed_revision

uint8 STATE_ACTIVE=0
uint8 STATE_HISTORICAL=1

uint8 FACE_NEG_X=1
uint8 FACE_POS_X=2
uint8 FACE_NEG_Y=4
uint8 FACE_POS_Y=8
uint8 FACE_NEG_Z=16
uint8 FACE_POS_Z=32

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  # Pseudo-constants
  STATE_ACTIVE = 0
  STATE_HISTORICAL = 1
  FACE_NEG_X = 1
  FACE_POS_X = 2
  FACE_NEG_Y = 4
  FACE_POS_Y = 8
  FACE_NEG_Z = 16
  FACE_POS_Z = 32

  __slots__ = ['id','position','clearance','degree','state','is_expandable','portal_mask','expansion_mask','node_revision','last_observed_revision']
  _slot_types = ['uint64','geometry_msgs/Point','float32','uint32','uint8','bool','uint8','uint8','uint64','uint64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,position,clearance,degree,state,is_expandable,portal_mask,expansion_mask,node_revision,last_observed_revision

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TopologyExpansionPoint, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.clearance is None:
        self.clearance = 0.
      if self.degree is None:
        self.degree = 0
      if self.state is None:
        self.state = 0
      if self.is_expandable is None:
        self.is_expandable = False
      if self.portal_mask is None:
        self.portal_mask = 0
      if self.expansion_mask is None:
        self.expansion_mask = 0
      if self.node_revision is None:
        self.node_revision = 0
      if self.last_observed_revision is None:
        self.last_observed_revision = 0
    else:
      self.id = 0
      self.position = geometry_msgs.msg.Point()
      self.clearance = 0.
      self.degree = 0
      self.state = 0
      self.is_expandable = False
      self.portal_mask = 0
      self.expansion_mask = 0
      self.node_revision = 0
      self.last_observed_revision = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Q3dfI4B2Q().pack(_x.id, _x.position.x, _x.position.y, _x.position.z, _x.clearance, _x.degree, _x.state, _x.is_expandable, _x.portal_mask, _x.expansion_mask, _x.node_revision, _x.last_observed_revision))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 60
      (_x.id, _x.position.x, _x.position.y, _x.position.z, _x.clearance, _x.degree, _x.state, _x.is_expandable, _x.portal_mask, _x.expansion_mask, _x.node_revision, _x.last_observed_revision,) = _get_struct_Q3dfI4B2Q().unpack(str[start:end])
      self.is_expandable = bool(self.is_expandable)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Q3dfI4B2Q().pack(_x.id, _x.position.x, _x.position.y, _x.position.z, _x.clearance, _x.degree, _x.state, _x.is_expandable, _x.portal_mask, _x.expansion_mask, _x.node_revision, _x.last_observed_revision))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 60
      (_x.id, _x.position.x, _x.position.y, _x.position.z, _x.clearance, _x.degree, _x.state, _x.is_expandable, _x.portal_mask, _x.expansion_mask, _x.node_revision, _x.last_observed_revision,) = _get_struct_Q3dfI4B2Q().unpack(str[start:end])
      self.is_expandable = bool(self.is_expandable)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Q3dfI4B2Q = None
def _get_struct_Q3dfI4B2Q():
    global _struct_Q3dfI4B2Q
    if _struct_Q3dfI4B2Q is None:
        _struct_Q3dfI4B2Q = struct.Struct("<Q3dfI4B2Q")
    return _struct_Q3dfI4B2Q
