# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from general_planner/TopologyFrontierPointArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import general_planner.msg
import geometry_msgs.msg
import std_msgs.msg

class TopologyFrontierPointArray(genpy.Message):
  _md5sum = "f5e719cb1deffd26eccf781f08569663"
  _type = "general_planner/TopologyFrontierPointArray"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# Latched full snapshot. Every point is an active topology node with at least
# one evidence-backed KNOWN_FREE-to-UNKNOWN direction.

std_msgs/Header header
uint64 world_epoch
uint64 map_revision
uint64 topology_revision
uint32 topology_node_count
uint32 frontier_count
TopologyFrontierPoint[] points

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: general_planner/TopologyFrontierPoint
# A public ACTIVE topology node attached to a current KNOWN_FREE-to-UNKNOWN
# map boundary. `position` is the safe topology anchor; `boundary_position`
# is the final known-free sample directly before UNKNOWN.

uint64 id
geometry_msgs/Point position
geometry_msgs/Point boundary_position
geometry_msgs/Vector3 boundary_normal
float32 clearance
float32 boundary_distance
uint32 degree
uint8 state
uint8 unknown_direction_mask
uint8 unknown_direction_count
uint64 node_revision
uint64 last_observed_revision

uint8 STATE_ACTIVE=0
uint8 STATE_HISTORICAL=1

uint8 FACE_NEG_X=1
uint8 FACE_POS_X=2
uint8 FACE_NEG_Y=4
uint8 FACE_POS_Y=8
uint8 FACE_NEG_Z=16
uint8 FACE_POS_Z=32

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','world_epoch','map_revision','topology_revision','topology_node_count','frontier_count','points']
  _slot_types = ['std_msgs/Header','uint64','uint64','uint64','uint32','uint32','general_planner/TopologyFrontierPoint[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,world_epoch,map_revision,topology_revision,topology_node_count,frontier_count,points

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TopologyFrontierPointArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.world_epoch is None:
        self.world_epoch = 0
      if self.map_revision is None:
        self.map_revision = 0
      if self.topology_revision is None:
        self.topology_revision = 0
      if self.topology_node_count is None:
        self.topology_node_count = 0
      if self.frontier_count is None:
        self.frontier_count = 0
      if self.points is None:
        self.points = []
    else:
      self.header = std_msgs.msg.Header()
      self.world_epoch = 0
      self.map_revision = 0
      self.topology_revision = 0
      self.topology_node_count = 0
      self.frontier_count = 0
      self.points = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3Q2I().pack(_x.world_epoch, _x.map_revision, _x.topology_revision, _x.topology_node_count, _x.frontier_count))
      length = len(self.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.points:
        _x = val1.id
        buff.write(_get_struct_Q().pack(_x))
        _v1 = val1.position
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v2 = val1.boundary_position
        _x = _v2
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v3 = val1.boundary_normal
        _x = _v3
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_2fI3B2Q().pack(_x.clearance, _x.boundary_distance, _x.degree, _x.state, _x.unknown_direction_mask, _x.unknown_direction_count, _x.node_revision, _x.last_observed_revision))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.points is None:
        self.points = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.world_epoch, _x.map_revision, _x.topology_revision, _x.topology_node_count, _x.frontier_count,) = _get_struct_3Q2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.points = []
      for i in range(0, length):
        val1 = general_planner.msg.TopologyFrontierPoint()
        start = end
        end += 8
        (val1.id,) = _get_struct_Q().unpack(str[start:end])
        _v4 = val1.position
        _x = _v4
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v5 = val1.boundary_position
        _x = _v5
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v6 = val1.boundary_normal
        _x = _v6
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _x = val1
        start = end
        end += 31
        (_x.clearance, _x.boundary_distance, _x.degree, _x.state, _x.unknown_direction_mask, _x.unknown_direction_count, _x.node_revision, _x.last_observed_revision,) = _get_struct_2fI3B2Q().unpack(str[start:end])
        self.points.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3Q2I().pack(_x.world_epoch, _x.map_revision, _x.topology_revision, _x.topology_node_count, _x.frontier_count))
      length = len(self.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.points:
        _x = val1.id
        buff.write(_get_struct_Q().pack(_x))
        _v7 = val1.position
        _x = _v7
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v8 = val1.boundary_position
        _x = _v8
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v9 = val1.boundary_normal
        _x = _v9
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_2fI3B2Q().pack(_x.clearance, _x.boundary_distance, _x.degree, _x.state, _x.unknown_direction_mask, _x.unknown_direction_count, _x.node_revision, _x.last_observed_revision))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.points is None:
        self.points = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.world_epoch, _x.map_revision, _x.topology_revision, _x.topology_node_count, _x.frontier_count,) = _get_struct_3Q2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.points = []
      for i in range(0, length):
        val1 = general_planner.msg.TopologyFrontierPoint()
        start = end
        end += 8
        (val1.id,) = _get_struct_Q().unpack(str[start:end])
        _v10 = val1.position
        _x = _v10
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v11 = val1.boundary_position
        _x = _v11
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v12 = val1.boundary_normal
        _x = _v12
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _x = val1
        start = end
        end += 31
        (_x.clearance, _x.boundary_distance, _x.degree, _x.state, _x.unknown_direction_mask, _x.unknown_direction_count, _x.node_revision, _x.last_observed_revision,) = _get_struct_2fI3B2Q().unpack(str[start:end])
        self.points.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2fI3B2Q = None
def _get_struct_2fI3B2Q():
    global _struct_2fI3B2Q
    if _struct_2fI3B2Q is None:
        _struct_2fI3B2Q = struct.Struct("<2fI3B2Q")
    return _struct_2fI3B2Q
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3Q2I = None
def _get_struct_3Q2I():
    global _struct_3Q2I
    if _struct_3Q2I is None:
        _struct_3Q2I = struct.Struct("<3Q2I")
    return _struct_3Q2I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_Q = None
def _get_struct_Q():
    global _struct_Q
    if _struct_Q is None:
        _struct_Q = struct.Struct("<Q")
    return _struct_Q
