# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from general_planner/TopologyFrontierPoint.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class TopologyFrontierPoint(genpy.Message):
  _md5sum = "4e1416454c4689c632966440c50e3df5"
  _type = "general_planner/TopologyFrontierPoint"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# A public ACTIVE topology node attached to a current KNOWN_FREE-to-UNKNOWN
# map boundary. `position` is the safe topology anchor; `boundary_position`
# is the final known-free sample directly before UNKNOWN.

uint64 id
geometry_msgs/Point position
geometry_msgs/Point boundary_position
geometry_msgs/Vector3 boundary_normal
float32 clearance
float32 boundary_distance
uint32 degree
uint8 state
uint8 unknown_direction_mask
uint8 unknown_direction_count
uint64 node_revision
uint64 last_observed_revision

uint8 STATE_ACTIVE=0
uint8 STATE_HISTORICAL=1

uint8 FACE_NEG_X=1
uint8 FACE_POS_X=2
uint8 FACE_NEG_Y=4
uint8 FACE_POS_Y=8
uint8 FACE_NEG_Z=16
uint8 FACE_POS_Z=32

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  # Pseudo-constants
  STATE_ACTIVE = 0
  STATE_HISTORICAL = 1
  FACE_NEG_X = 1
  FACE_POS_X = 2
  FACE_NEG_Y = 4
  FACE_POS_Y = 8
  FACE_NEG_Z = 16
  FACE_POS_Z = 32

  __slots__ = ['id','position','boundary_position','boundary_normal','clearance','boundary_distance','degree','state','unknown_direction_mask','unknown_direction_count','node_revision','last_observed_revision']
  _slot_types = ['uint64','geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Vector3','float32','float32','uint32','uint8','uint8','uint8','uint64','uint64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,position,boundary_position,boundary_normal,clearance,boundary_distance,degree,state,unknown_direction_mask,unknown_direction_count,node_revision,last_observed_revision

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TopologyFrontierPoint, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.boundary_position is None:
        self.boundary_position = geometry_msgs.msg.Point()
      if self.boundary_normal is None:
        self.boundary_normal = geometry_msgs.msg.Vector3()
      if self.clearance is None:
        self.clearance = 0.
      if self.boundary_distance is None:
        self.boundary_distance = 0.
      if self.degree is None:
        self.degree = 0
      if self.state is None:
        self.state = 0
      if self.unknown_direction_mask is None:
        self.unknown_direction_mask = 0
      if self.unknown_direction_count is None:
        self.unknown_direction_count = 0
      if self.node_revision is None:
        self.node_revision = 0
      if self.last_observed_revision is None:
        self.last_observed_revision = 0
    else:
      self.id = 0
      self.position = geometry_msgs.msg.Point()
      self.boundary_position = geometry_msgs.msg.Point()
      self.boundary_normal = geometry_msgs.msg.Vector3()
      self.clearance = 0.
      self.boundary_distance = 0.
      self.degree = 0
      self.state = 0
      self.unknown_direction_mask = 0
      self.unknown_direction_count = 0
      self.node_revision = 0
      self.last_observed_revision = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Q9d2fI3B2Q().pack(_x.id, _x.position.x, _x.position.y, _x.position.z, _x.boundary_position.x, _x.boundary_position.y, _x.boundary_position.z, _x.boundary_normal.x, _x.boundary_normal.y, _x.boundary_normal.z, _x.clearance, _x.boundary_distance, _x.degree, _x.state, _x.unknown_direction_mask, _x.unknown_direction_count, _x.node_revision, _x.last_observed_revision))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.boundary_position is None:
        self.boundary_position = geometry_msgs.msg.Point()
      if self.boundary_normal is None:
        self.boundary_normal = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 111
      (_x.id, _x.position.x, _x.position.y, _x.position.z, _x.boundary_position.x, _x.boundary_position.y, _x.boundary_position.z, _x.boundary_normal.x, _x.boundary_normal.y, _x.boundary_normal.z, _x.clearance, _x.boundary_distance, _x.degree, _x.state, _x.unknown_direction_mask, _x.unknown_direction_count, _x.node_revision, _x.last_observed_revision,) = _get_struct_Q9d2fI3B2Q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Q9d2fI3B2Q().pack(_x.id, _x.position.x, _x.position.y, _x.position.z, _x.boundary_position.x, _x.boundary_position.y, _x.boundary_position.z, _x.boundary_normal.x, _x.boundary_normal.y, _x.boundary_normal.z, _x.clearance, _x.boundary_distance, _x.degree, _x.state, _x.unknown_direction_mask, _x.unknown_direction_count, _x.node_revision, _x.last_observed_revision))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.boundary_position is None:
        self.boundary_position = geometry_msgs.msg.Point()
      if self.boundary_normal is None:
        self.boundary_normal = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 111
      (_x.id, _x.position.x, _x.position.y, _x.position.z, _x.boundary_position.x, _x.boundary_position.y, _x.boundary_position.z, _x.boundary_normal.x, _x.boundary_normal.y, _x.boundary_normal.z, _x.clearance, _x.boundary_distance, _x.degree, _x.state, _x.unknown_direction_mask, _x.unknown_direction_count, _x.node_revision, _x.last_observed_revision,) = _get_struct_Q9d2fI3B2Q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Q9d2fI3B2Q = None
def _get_struct_Q9d2fI3B2Q():
    global _struct_Q9d2fI3B2Q
    if _struct_Q9d2fI3B2Q is None:
        _struct_Q9d2fI3B2Q = struct.Struct("<Q9d2fI3B2Q")
    return _struct_Q9d2fI3B2Q
