task_planner:
  start_trigger_type: 2
  start_program_delay: 1.0
  odom_timeout: 1.0
  publish_dt: 0.5
  switch_dis: 1.0
  frame_id: "world"

  odom_topic: "/lidar_slam/odom"
  task_mode_topic: "/planning/task_mode"
  goal_pub_topic: "/planning/click_goal"
  tracking_target_odom_topic: "/tracking/target_odom"
  tracking_target_path_topic: "/tracking/target_path"
  tracking_target_prediction_topic: "/tracking/target_prediction"
  perching_surface_odom_topic: "/perching/surface_odom"
  path_pub_topic: "/task_planner/path"
  marker_topic: "mkr"

  default_task_mode: "exploration"
  tasks:
    - name: "epic_global_exploration"
      mode: "exploration"
      position: [15.0, 0.0, 1.5]
      switch_dis: 1.0
      publish_dt: 0.5
      hold_duration: -1.0
