// Generated by gencpp from file quadrotor_msgs/InspectionPointSet.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_INSPECTIONPOINTSET_H
#define QUADROTOR_MSGS_MESSAGE_INSPECTIONPOINTSET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <quadrotor_msgs/InspectionPoint.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct InspectionPointSet_
{
  typedef InspectionPointSet_<ContainerAllocator> Type;

  InspectionPointSet_()
    : Point_set()  {
    }
  InspectionPointSet_(const ContainerAllocator& _alloc)
    : Point_set(_alloc)  {
  (void)_alloc;
    }



   typedef  ::quadrotor_msgs::InspectionPoint_<ContainerAllocator>  _Point_set_type;
  _Point_set_type Point_set;





  typedef boost::shared_ptr< ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator> const> ConstPtr;

}; // struct InspectionPointSet_

typedef ::quadrotor_msgs::InspectionPointSet_<std::allocator<void> > InspectionPointSet;

typedef boost::shared_ptr< ::quadrotor_msgs::InspectionPointSet > InspectionPointSetPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::InspectionPointSet const> InspectionPointSetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator2> & rhs)
{
  return lhs.Point_set == rhs.Point_set;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ad14709e12727657e69b53b65581176";
  }

  static const char* value(const ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ad14709e1272765ULL;
  static const uint64_t static_value2 = 0x7e69b53b65581176ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/InspectionPointSet";
  }

  static const char* value(const ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "InspectionPoint Point_set\n"
"================================================================================\n"
"MSG: quadrotor_msgs/InspectionPoint\n"
"std_msgs/Header                 header\n"
"uint64 seq\n"
"#attribute of the inspection point\n"
"bool                            IsInspectionPoint\n"
"geometry_msgs/Point             point                           #航点\n"
"bool                            free_nav                        #自由导航\n"
"bool                            ENABLE_YAW                      #使能航点yaw\n"
"float64                         point_yaw                       #航点yaw\n"
"float64                         stop_duration                   #航点处的停留时间\n"
"uint16[]                        ACTIONS                         #航点处需要执行的动作\n"
"geometry_msgs/Point             point_vel                       #用户指定的航点的速度默认且必须为0，为了确保轨迹平直而插入的点可以不为0\n"
"bool                            FORCEGOAL                       #用户给的强制点，接收到该点时可以在不是waittarget状态下直接进行规划    \n"
"\n"
"#attribute of the inspection line\n"
"float64                         line_vel                        #航线上的速度 发布前需要提前确认是否与point vel冲突\n"
"bool                            ENABLE_LINE_AVOIDANCE           #是否沿线避障，若不避障则遇到障碍物急停，若避障则遇到障碍物后急停然后择机避障\n"
"float64                         avoidance_radius                #沿着航线上的避障半径\n"
"\n"
"                         \n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Point_set);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InspectionPointSet_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::InspectionPointSet_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "Point_set: ";
    Printer< ::quadrotor_msgs::InspectionPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.Point_set);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_INSPECTIONPOINTSET_H
