// Generated by gencpp from file quadrotor_msgs/InspectionPoint.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_INSPECTIONPOINT_H
#define QUADROTOR_MSGS_MESSAGE_INSPECTIONPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct InspectionPoint_
{
  typedef InspectionPoint_<ContainerAllocator> Type;

  InspectionPoint_()
    : header()
    , seq(0)
    , IsInspectionPoint(false)
    , point()
    , free_nav(false)
    , ENABLE_YAW(false)
    , point_yaw(0.0)
    , stop_duration(0.0)
    , ACTIONS()
    , point_vel()
    , FORCEGOAL(false)
    , line_vel(0.0)
    , ENABLE_LINE_AVOIDANCE(false)
    , avoidance_radius(0.0)  {
    }
  InspectionPoint_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , seq(0)
    , IsInspectionPoint(false)
    , point(_alloc)
    , free_nav(false)
    , ENABLE_YAW(false)
    , point_yaw(0.0)
    , stop_duration(0.0)
    , ACTIONS(_alloc)
    , point_vel(_alloc)
    , FORCEGOAL(false)
    , line_vel(0.0)
    , ENABLE_LINE_AVOIDANCE(false)
    , avoidance_radius(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _seq_type;
  _seq_type seq;

   typedef uint8_t _IsInspectionPoint_type;
  _IsInspectionPoint_type IsInspectionPoint;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;

   typedef uint8_t _free_nav_type;
  _free_nav_type free_nav;

   typedef uint8_t _ENABLE_YAW_type;
  _ENABLE_YAW_type ENABLE_YAW;

   typedef double _point_yaw_type;
  _point_yaw_type point_yaw;

   typedef double _stop_duration_type;
  _stop_duration_type stop_duration;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _ACTIONS_type;
  _ACTIONS_type ACTIONS;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_vel_type;
  _point_vel_type point_vel;

   typedef uint8_t _FORCEGOAL_type;
  _FORCEGOAL_type FORCEGOAL;

   typedef double _line_vel_type;
  _line_vel_type line_vel;

   typedef uint8_t _ENABLE_LINE_AVOIDANCE_type;
  _ENABLE_LINE_AVOIDANCE_type ENABLE_LINE_AVOIDANCE;

   typedef double _avoidance_radius_type;
  _avoidance_radius_type avoidance_radius;





  typedef boost::shared_ptr< ::quadrotor_msgs::InspectionPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::InspectionPoint_<ContainerAllocator> const> ConstPtr;

}; // struct InspectionPoint_

typedef ::quadrotor_msgs::InspectionPoint_<std::allocator<void> > InspectionPoint;

typedef boost::shared_ptr< ::quadrotor_msgs::InspectionPoint > InspectionPointPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::InspectionPoint const> InspectionPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::InspectionPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::InspectionPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::InspectionPoint_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::InspectionPoint_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.seq == rhs.seq &&
    lhs.IsInspectionPoint == rhs.IsInspectionPoint &&
    lhs.point == rhs.point &&
    lhs.free_nav == rhs.free_nav &&
    lhs.ENABLE_YAW == rhs.ENABLE_YAW &&
    lhs.point_yaw == rhs.point_yaw &&
    lhs.stop_duration == rhs.stop_duration &&
    lhs.ACTIONS == rhs.ACTIONS &&
    lhs.point_vel == rhs.point_vel &&
    lhs.FORCEGOAL == rhs.FORCEGOAL &&
    lhs.line_vel == rhs.line_vel &&
    lhs.ENABLE_LINE_AVOIDANCE == rhs.ENABLE_LINE_AVOIDANCE &&
    lhs.avoidance_radius == rhs.avoidance_radius;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::InspectionPoint_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::InspectionPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::InspectionPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::InspectionPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::InspectionPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::InspectionPoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::InspectionPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::InspectionPoint_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::InspectionPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7d104e0cc074bae4dd5b0d72d844e70";
  }

  static const char* value(const ::quadrotor_msgs::InspectionPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7d104e0cc074baeULL;
  static const uint64_t static_value2 = 0x4dd5b0d72d844e70ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::InspectionPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/InspectionPoint";
  }

  static const char* value(const ::quadrotor_msgs::InspectionPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::InspectionPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header                 header\n"
"uint64 seq\n"
"#attribute of the inspection point\n"
"bool                            IsInspectionPoint\n"
"geometry_msgs/Point             point                           #航点\n"
"bool                            free_nav                        #自由导航\n"
"bool                            ENABLE_YAW                      #使能航点yaw\n"
"float64                         point_yaw                       #航点yaw\n"
"float64                         stop_duration                   #航点处的停留时间\n"
"uint16[]                        ACTIONS                         #航点处需要执行的动作\n"
"geometry_msgs/Point             point_vel                       #用户指定的航点的速度默认且必须为0，为了确保轨迹平直而插入的点可以不为0\n"
"bool                            FORCEGOAL                       #用户给的强制点，接收到该点时可以在不是waittarget状态下直接进行规划    \n"
"\n"
"#attribute of the inspection line\n"
"float64                         line_vel                        #航线上的速度 发布前需要提前确认是否与point vel冲突\n"
"bool                            ENABLE_LINE_AVOIDANCE           #是否沿线避障，若不避障则遇到障碍物急停，若避障则遇到障碍物后急停然后择机避障\n"
"float64                         avoidance_radius                #沿着航线上的避障半径\n"
"\n"
"                         \n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::quadrotor_msgs::InspectionPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::InspectionPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.seq);
      stream.next(m.IsInspectionPoint);
      stream.next(m.point);
      stream.next(m.free_nav);
      stream.next(m.ENABLE_YAW);
      stream.next(m.point_yaw);
      stream.next(m.stop_duration);
      stream.next(m.ACTIONS);
      stream.next(m.point_vel);
      stream.next(m.FORCEGOAL);
      stream.next(m.line_vel);
      stream.next(m.ENABLE_LINE_AVOIDANCE);
      stream.next(m.avoidance_radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InspectionPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::InspectionPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::InspectionPoint_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "seq: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.seq);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "IsInspectionPoint: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.IsInspectionPoint);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "point: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "free_nav: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.free_nav);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ENABLE_YAW: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ENABLE_YAW);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "point_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.point_yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stop_duration: ";
    Printer<double>::stream(s, indent + "  ", v.stop_duration);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ACTIONS: ";
    if (v.ACTIONS.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.ACTIONS.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint16_t>::stream(s, true ? std::string() : indent + "    ", v.ACTIONS[i]);
    }
    if (v.ACTIONS.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "point_vel: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point_vel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "FORCEGOAL: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.FORCEGOAL);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "line_vel: ";
    Printer<double>::stream(s, indent + "  ", v.line_vel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ENABLE_LINE_AVOIDANCE: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ENABLE_LINE_AVOIDANCE);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "avoidance_radius: ";
    Printer<double>::stream(s, indent + "  ", v.avoidance_radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_INSPECTIONPOINT_H
