// Generated by gencpp from file quadrotor_msgs/Pause.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_PAUSE_H
#define QUADROTOR_MSGS_MESSAGE_PAUSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct Pause_
{
  typedef Pause_<ContainerAllocator> Type;

  Pause_()
    : seq(0)
    , pasue(false)  {
    }
  Pause_(const ContainerAllocator& _alloc)
    : seq(0)
    , pasue(false)  {
  (void)_alloc;
    }



   typedef uint64_t _seq_type;
  _seq_type seq;

   typedef uint8_t _pasue_type;
  _pasue_type pasue;





  typedef boost::shared_ptr< ::quadrotor_msgs::Pause_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::Pause_<ContainerAllocator> const> ConstPtr;

}; // struct Pause_

typedef ::quadrotor_msgs::Pause_<std::allocator<void> > Pause;

typedef boost::shared_ptr< ::quadrotor_msgs::Pause > PausePtr;
typedef boost::shared_ptr< ::quadrotor_msgs::Pause const> PauseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::Pause_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::Pause_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::Pause_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::Pause_<ContainerAllocator2> & rhs)
{
  return lhs.seq == rhs.seq &&
    lhs.pasue == rhs.pasue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::Pause_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::Pause_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::Pause_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::Pause_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::Pause_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::Pause_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::Pause_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::Pause_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::Pause_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45584844e5ad3adc72b5fdee186db8bf";
  }

  static const char* value(const ::quadrotor_msgs::Pause_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45584844e5ad3adcULL;
  static const uint64_t static_value2 = 0x72b5fdee186db8bfULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::Pause_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/Pause";
  }

  static const char* value(const ::quadrotor_msgs::Pause_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::Pause_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 seq\n"
"bool pasue\n"
;
  }

  static const char* value(const ::quadrotor_msgs::Pause_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::Pause_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.seq);
      stream.next(m.pasue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pause_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::Pause_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::Pause_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "seq: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.seq);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pasue: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pasue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_PAUSE_H
