// Generated by gencpp from file quadrotor_msgs/PlanState.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_PLANSTATE_H
#define QUADROTOR_MSGS_MESSAGE_PLANSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct PlanState_
{
  typedef PlanState_<ContainerAllocator> Type;

  PlanState_()
    : seq(0)
    , plan_state(0)  {
    }
  PlanState_(const ContainerAllocator& _alloc)
    : seq(0)
    , plan_state(0)  {
  (void)_alloc;
    }



   typedef uint64_t _seq_type;
  _seq_type seq;

   typedef uint8_t _plan_state_type;
  _plan_state_type plan_state;





  typedef boost::shared_ptr< ::quadrotor_msgs::PlanState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::PlanState_<ContainerAllocator> const> ConstPtr;

}; // struct PlanState_

typedef ::quadrotor_msgs::PlanState_<std::allocator<void> > PlanState;

typedef boost::shared_ptr< ::quadrotor_msgs::PlanState > PlanStatePtr;
typedef boost::shared_ptr< ::quadrotor_msgs::PlanState const> PlanStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::PlanState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::PlanState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::PlanState_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::PlanState_<ContainerAllocator2> & rhs)
{
  return lhs.seq == rhs.seq &&
    lhs.plan_state == rhs.plan_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::PlanState_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::PlanState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::PlanState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::PlanState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::PlanState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::PlanState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::PlanState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::PlanState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::PlanState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fae6e295ad2bb283b8bf04fab29ba70f";
  }

  static const char* value(const ::quadrotor_msgs::PlanState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfae6e295ad2bb283ULL;
  static const uint64_t static_value2 = 0xb8bf04fab29ba70fULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::PlanState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/PlanState";
  }

  static const char* value(const ::quadrotor_msgs::PlanState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::PlanState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 seq\n"
"uint8 plan_state\n"
;
  }

  static const char* value(const ::quadrotor_msgs::PlanState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::PlanState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.seq);
      stream.next(m.plan_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::PlanState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::PlanState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "seq: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.seq);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "plan_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.plan_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_PLANSTATE_H
