// Generated by gencpp from file quadrotor_msgs/Px4State.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_PX4STATE_H
#define QUADROTOR_MSGS_MESSAGE_PX4STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct Px4State_
{
  typedef Px4State_<ContainerAllocator> Type;

  Px4State_()
    : seq(0)
    , px4_state(0)  {
    }
  Px4State_(const ContainerAllocator& _alloc)
    : seq(0)
    , px4_state(0)  {
  (void)_alloc;
    }



   typedef uint64_t _seq_type;
  _seq_type seq;

   typedef uint8_t _px4_state_type;
  _px4_state_type px4_state;





  typedef boost::shared_ptr< ::quadrotor_msgs::Px4State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::Px4State_<ContainerAllocator> const> ConstPtr;

}; // struct Px4State_

typedef ::quadrotor_msgs::Px4State_<std::allocator<void> > Px4State;

typedef boost::shared_ptr< ::quadrotor_msgs::Px4State > Px4StatePtr;
typedef boost::shared_ptr< ::quadrotor_msgs::Px4State const> Px4StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::Px4State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::Px4State_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::Px4State_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::Px4State_<ContainerAllocator2> & rhs)
{
  return lhs.seq == rhs.seq &&
    lhs.px4_state == rhs.px4_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::Px4State_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::Px4State_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::Px4State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::Px4State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::Px4State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::Px4State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::Px4State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::Px4State_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::Px4State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e44ef5fb7304c3c64e9c04ed189cf780";
  }

  static const char* value(const ::quadrotor_msgs::Px4State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe44ef5fb7304c3c6ULL;
  static const uint64_t static_value2 = 0x4e9c04ed189cf780ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::Px4State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/Px4State";
  }

  static const char* value(const ::quadrotor_msgs::Px4State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::Px4State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 seq\n"
"uint8 px4_state\n"
;
  }

  static const char* value(const ::quadrotor_msgs::Px4State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::Px4State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.seq);
      stream.next(m.px4_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Px4State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::Px4State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::Px4State_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "seq: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.seq);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "px4_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.px4_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_PX4STATE_H
