// Generated by gencpp from file general_planner/ExplorationTrajectory.msg
// DO NOT EDIT!


#ifndef GENERAL_PLANNER_MESSAGE_EXPLORATIONTRAJECTORY_H
#define GENERAL_PLANNER_MESSAGE_EXPLORATIONTRAJECTORY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <traj_utils/PolyTraj.h>
#include <traj_utils/PolyTraj.h>

namespace general_planner
{
template <class ContainerAllocator>
struct ExplorationTrajectory_
{
  typedef ExplorationTrajectory_<ContainerAllocator> Type;

  ExplorationTrajectory_()
    : task_epoch(0)
    , task_id()
    , position()
    , yaw()  {
    }
  ExplorationTrajectory_(const ContainerAllocator& _alloc)
    : task_epoch(0)
    , task_id(_alloc)
    , position(_alloc)
    , yaw(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _task_epoch_type;
  _task_epoch_type task_epoch;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_id_type;
  _task_id_type task_id;

   typedef  ::traj_utils::PolyTraj_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::traj_utils::PolyTraj_<ContainerAllocator>  _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::general_planner::ExplorationTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::general_planner::ExplorationTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct ExplorationTrajectory_

typedef ::general_planner::ExplorationTrajectory_<std::allocator<void> > ExplorationTrajectory;

typedef boost::shared_ptr< ::general_planner::ExplorationTrajectory > ExplorationTrajectoryPtr;
typedef boost::shared_ptr< ::general_planner::ExplorationTrajectory const> ExplorationTrajectoryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::general_planner::ExplorationTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::general_planner::ExplorationTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::general_planner::ExplorationTrajectory_<ContainerAllocator1> & lhs, const ::general_planner::ExplorationTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.task_epoch == rhs.task_epoch &&
    lhs.task_id == rhs.task_id &&
    lhs.position == rhs.position &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::general_planner::ExplorationTrajectory_<ContainerAllocator1> & lhs, const ::general_planner::ExplorationTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace general_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::general_planner::ExplorationTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::general_planner::ExplorationTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::ExplorationTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::ExplorationTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::ExplorationTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::ExplorationTrajectory_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::general_planner::ExplorationTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78945e84c09526734c24f8463f3e835a";
  }

  static const char* value(const ::general_planner::ExplorationTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78945e84c0952673ULL;
  static const uint64_t static_value2 = 0x4c24f8463f3e835aULL;
};

template<class ContainerAllocator>
struct DataType< ::general_planner::ExplorationTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "general_planner/ExplorationTrajectory";
  }

  static const char* value(const ::general_planner::ExplorationTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::general_planner::ExplorationTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 task_epoch\n"
"string task_id\n"
"traj_utils/PolyTraj position\n"
"traj_utils/PolyTraj yaw\n"
"\n"
"================================================================================\n"
"MSG: traj_utils/PolyTraj\n"
"int16 drone_id\n"
"int32 traj_id\n"
"time start_time\n"
"\n"
"uint8 order\n"
"float32[] coef_x\n"
"float32[] coef_y\n"
"float32[] coef_z\n"
"float32[] duration\n"
;
  }

  static const char* value(const ::general_planner::ExplorationTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::general_planner::ExplorationTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_epoch);
      stream.next(m.task_id);
      stream.next(m.position);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExplorationTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::general_planner::ExplorationTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::general_planner::ExplorationTrajectory_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "task_epoch: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.task_epoch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::traj_utils::PolyTraj_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer< ::traj_utils::PolyTraj_<ContainerAllocator> >::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GENERAL_PLANNER_MESSAGE_EXPLORATIONTRAJECTORY_H
