// Generated by gencpp from file general_planner/FrontierCluster.msg
// DO NOT EDIT!


#ifndef GENERAL_PLANNER_MESSAGE_FRONTIERCLUSTER_H
#define GENERAL_PLANNER_MESSAGE_FRONTIERCLUSTER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace general_planner
{
template <class ContainerAllocator>
struct FrontierCluster_
{
  typedef FrontierCluster_<ContainerAllocator> Type;

  FrontierCluster_()
    : id(0)
    , center()
    , normal()
    , best_viewpoint()
    , box_min()
    , box_max()
    , state(0)
    , is_reachable(false)
    , is_dormant(false)
    , is_new_cluster(false)
    , visible_gain(0.0)
    , score(0.0)
    , distance(0.0)  {
    }
  FrontierCluster_(const ContainerAllocator& _alloc)
    : id(0)
    , center(_alloc)
    , normal(_alloc)
    , best_viewpoint(_alloc)
    , box_min(_alloc)
    , box_max(_alloc)
    , state(0)
    , is_reachable(false)
    , is_dormant(false)
    , is_new_cluster(false)
    , visible_gain(0.0)
    , score(0.0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _normal_type;
  _normal_type normal;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _best_viewpoint_type;
  _best_viewpoint_type best_viewpoint;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _box_min_type;
  _box_min_type box_min;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _box_max_type;
  _box_max_type box_max;

   typedef uint8_t _state_type;
  _state_type state;

   typedef uint8_t _is_reachable_type;
  _is_reachable_type is_reachable;

   typedef uint8_t _is_dormant_type;
  _is_dormant_type is_dormant;

   typedef uint8_t _is_new_cluster_type;
  _is_new_cluster_type is_new_cluster;

   typedef float _visible_gain_type;
  _visible_gain_type visible_gain;

   typedef float _score_type;
  _score_type score;

   typedef float _distance_type;
  _distance_type distance;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STATE_ACTIVE)
  #undef STATE_ACTIVE
#endif
#if defined(_WIN32) && defined(STATE_SELECTED)
  #undef STATE_SELECTED
#endif
#if defined(_WIN32) && defined(STATE_PENDING_RETRY)
  #undef STATE_PENDING_RETRY
#endif
#if defined(_WIN32) && defined(STATE_SUSPENDED)
  #undef STATE_SUSPENDED
#endif
#if defined(_WIN32) && defined(STATE_DEFERRED_BRANCH)
  #undef STATE_DEFERRED_BRANCH
#endif
#if defined(_WIN32) && defined(STATE_VISITED)
  #undef STATE_VISITED
#endif
#if defined(_WIN32) && defined(STATE_BLACKLISTED)
  #undef STATE_BLACKLISTED
#endif

  enum {
    STATE_ACTIVE = 0u,
    STATE_SELECTED = 1u,
    STATE_PENDING_RETRY = 2u,
    STATE_SUSPENDED = 3u,
    STATE_DEFERRED_BRANCH = 4u,
    STATE_VISITED = 5u,
    STATE_BLACKLISTED = 6u,
  };


  typedef boost::shared_ptr< ::general_planner::FrontierCluster_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::general_planner::FrontierCluster_<ContainerAllocator> const> ConstPtr;

}; // struct FrontierCluster_

typedef ::general_planner::FrontierCluster_<std::allocator<void> > FrontierCluster;

typedef boost::shared_ptr< ::general_planner::FrontierCluster > FrontierClusterPtr;
typedef boost::shared_ptr< ::general_planner::FrontierCluster const> FrontierClusterConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::general_planner::FrontierCluster_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::general_planner::FrontierCluster_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::general_planner::FrontierCluster_<ContainerAllocator1> & lhs, const ::general_planner::FrontierCluster_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.center == rhs.center &&
    lhs.normal == rhs.normal &&
    lhs.best_viewpoint == rhs.best_viewpoint &&
    lhs.box_min == rhs.box_min &&
    lhs.box_max == rhs.box_max &&
    lhs.state == rhs.state &&
    lhs.is_reachable == rhs.is_reachable &&
    lhs.is_dormant == rhs.is_dormant &&
    lhs.is_new_cluster == rhs.is_new_cluster &&
    lhs.visible_gain == rhs.visible_gain &&
    lhs.score == rhs.score &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::general_planner::FrontierCluster_<ContainerAllocator1> & lhs, const ::general_planner::FrontierCluster_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace general_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::general_planner::FrontierCluster_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::general_planner::FrontierCluster_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::FrontierCluster_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::FrontierCluster_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::FrontierCluster_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::FrontierCluster_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::general_planner::FrontierCluster_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c5aa1a798a8e0d9ffb1c40d458e0b";
  }

  static const char* value(const ::general_planner::FrontierCluster_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c5aa1a798a8e0ULL;
  static const uint64_t static_value2 = 0xd9ffb1c40d458e0bULL;
};

template<class ContainerAllocator>
struct DataType< ::general_planner::FrontierCluster_<ContainerAllocator> >
{
  static const char* value()
  {
    return "general_planner/FrontierCluster";
  }

  static const char* value(const ::general_planner::FrontierCluster_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::general_planner::FrontierCluster_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Semantic frontier cluster exposed to upper layers / release consumers.\n"
"# This is not a voxel-center cloud; it mirrors ClusterInfo used by exploration.\n"
"\n"
"int32 id\n"
"\n"
"geometry_msgs/Point center\n"
"geometry_msgs/Vector3 normal\n"
"geometry_msgs/Pose best_viewpoint\n"
"geometry_msgs/Point box_min\n"
"geometry_msgs/Point box_max\n"
"\n"
"uint8 state\n"
"bool is_reachable\n"
"bool is_dormant\n"
"bool is_new_cluster\n"
"\n"
"float32 visible_gain\n"
"float32 score\n"
"float32 distance\n"
"\n"
"uint8 STATE_ACTIVE=0\n"
"uint8 STATE_SELECTED=1\n"
"uint8 STATE_PENDING_RETRY=2\n"
"uint8 STATE_SUSPENDED=3\n"
"uint8 STATE_DEFERRED_BRANCH=4\n"
"uint8 STATE_VISITED=5\n"
"uint8 STATE_BLACKLISTED=6\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::general_planner::FrontierCluster_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::general_planner::FrontierCluster_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.center);
      stream.next(m.normal);
      stream.next(m.best_viewpoint);
      stream.next(m.box_min);
      stream.next(m.box_max);
      stream.next(m.state);
      stream.next(m.is_reachable);
      stream.next(m.is_dormant);
      stream.next(m.is_new_cluster);
      stream.next(m.visible_gain);
      stream.next(m.score);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FrontierCluster_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::general_planner::FrontierCluster_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::general_planner::FrontierCluster_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "center: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "normal: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.normal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "best_viewpoint: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.best_viewpoint);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "box_min: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.box_min);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "box_max: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.box_max);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_reachable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_reachable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_dormant: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_dormant);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_new_cluster: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_new_cluster);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "visible_gain: ";
    Printer<float>::stream(s, indent + "  ", v.visible_gain);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "score: ";
    Printer<float>::stream(s, indent + "  ", v.score);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GENERAL_PLANNER_MESSAGE_FRONTIERCLUSTER_H
