// Generated by gencpp from file general_planner/NavigationGoalAck.msg
// DO NOT EDIT!


#ifndef GENERAL_PLANNER_MESSAGE_NAVIGATIONGOALACK_H
#define GENERAL_PLANNER_MESSAGE_NAVIGATIONGOALACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace general_planner
{
template <class ContainerAllocator>
struct NavigationGoalAck_
{
  typedef NavigationGoalAck_<ContainerAllocator> Type;

  NavigationGoalAck_()
    : task_epoch(0)
    , request_id(0)
    , goal_sequence(0)
    , result(0)
    , reason()  {
    }
  NavigationGoalAck_(const ContainerAllocator& _alloc)
    : task_epoch(0)
    , request_id(0)
    , goal_sequence(0)
    , result(0)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _task_epoch_type;
  _task_epoch_type task_epoch;

   typedef uint64_t _request_id_type;
  _request_id_type request_id;

   typedef uint64_t _goal_sequence_type;
  _goal_sequence_type goal_sequence;

   typedef uint8_t _result_type;
  _result_type result;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(REJECTED)
  #undef REJECTED
#endif
#if defined(_WIN32) && defined(ACCEPTED)
  #undef ACCEPTED
#endif
#if defined(_WIN32) && defined(ALREADY_ACTIVE)
  #undef ALREADY_ACTIVE
#endif

  enum {
    REJECTED = 0u,
    ACCEPTED = 1u,
    ALREADY_ACTIVE = 2u,
  };


  typedef boost::shared_ptr< ::general_planner::NavigationGoalAck_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::general_planner::NavigationGoalAck_<ContainerAllocator> const> ConstPtr;

}; // struct NavigationGoalAck_

typedef ::general_planner::NavigationGoalAck_<std::allocator<void> > NavigationGoalAck;

typedef boost::shared_ptr< ::general_planner::NavigationGoalAck > NavigationGoalAckPtr;
typedef boost::shared_ptr< ::general_planner::NavigationGoalAck const> NavigationGoalAckConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::general_planner::NavigationGoalAck_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::general_planner::NavigationGoalAck_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::general_planner::NavigationGoalAck_<ContainerAllocator1> & lhs, const ::general_planner::NavigationGoalAck_<ContainerAllocator2> & rhs)
{
  return lhs.task_epoch == rhs.task_epoch &&
    lhs.request_id == rhs.request_id &&
    lhs.goal_sequence == rhs.goal_sequence &&
    lhs.result == rhs.result &&
    lhs.reason == rhs.reason;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::general_planner::NavigationGoalAck_<ContainerAllocator1> & lhs, const ::general_planner::NavigationGoalAck_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace general_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::general_planner::NavigationGoalAck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::general_planner::NavigationGoalAck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::NavigationGoalAck_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::NavigationGoalAck_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::NavigationGoalAck_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::NavigationGoalAck_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::general_planner::NavigationGoalAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e9581ee72cea47d592ddaf6ef4cba75";
  }

  static const char* value(const ::general_planner::NavigationGoalAck_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e9581ee72cea47dULL;
  static const uint64_t static_value2 = 0x592ddaf6ef4cba75ULL;
};

template<class ContainerAllocator>
struct DataType< ::general_planner::NavigationGoalAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "general_planner/NavigationGoalAck";
  }

  static const char* value(const ::general_planner::NavigationGoalAck_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::general_planner::NavigationGoalAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 REJECTED=0\n"
"uint8 ACCEPTED=1\n"
"uint8 ALREADY_ACTIVE=2\n"
"uint64 task_epoch\n"
"uint64 request_id\n"
"uint64 goal_sequence\n"
"uint8 result\n"
"string reason\n"
;
  }

  static const char* value(const ::general_planner::NavigationGoalAck_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::general_planner::NavigationGoalAck_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_epoch);
      stream.next(m.request_id);
      stream.next(m.goal_sequence);
      stream.next(m.result);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigationGoalAck_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::general_planner::NavigationGoalAck_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::general_planner::NavigationGoalAck_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "task_epoch: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.task_epoch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "request_id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.request_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal_sequence: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.goal_sequence);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GENERAL_PLANNER_MESSAGE_NAVIGATIONGOALACK_H
