// Generated by gencpp from file general_planner/NavigationGoalRequest.msg
// DO NOT EDIT!


#ifndef GENERAL_PLANNER_MESSAGE_NAVIGATIONGOALREQUEST_H
#define GENERAL_PLANNER_MESSAGE_NAVIGATIONGOALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace general_planner
{
template <class ContainerAllocator>
struct NavigationGoalRequest_
{
  typedef NavigationGoalRequest_<ContainerAllocator> Type;

  NavigationGoalRequest_()
    : task_epoch(0)
    , request_id(0)
    , goal()
    , preserve_message_height(false)  {
    }
  NavigationGoalRequest_(const ContainerAllocator& _alloc)
    : task_epoch(0)
    , request_id(0)
    , goal(_alloc)
    , preserve_message_height(false)  {
  (void)_alloc;
    }



   typedef uint64_t _task_epoch_type;
  _task_epoch_type task_epoch;

   typedef uint64_t _request_id_type;
  _request_id_type request_id;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _goal_type;
  _goal_type goal;

   typedef uint8_t _preserve_message_height_type;
  _preserve_message_height_type preserve_message_height;





  typedef boost::shared_ptr< ::general_planner::NavigationGoalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::general_planner::NavigationGoalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NavigationGoalRequest_

typedef ::general_planner::NavigationGoalRequest_<std::allocator<void> > NavigationGoalRequest;

typedef boost::shared_ptr< ::general_planner::NavigationGoalRequest > NavigationGoalRequestPtr;
typedef boost::shared_ptr< ::general_planner::NavigationGoalRequest const> NavigationGoalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::general_planner::NavigationGoalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::general_planner::NavigationGoalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::general_planner::NavigationGoalRequest_<ContainerAllocator1> & lhs, const ::general_planner::NavigationGoalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.task_epoch == rhs.task_epoch &&
    lhs.request_id == rhs.request_id &&
    lhs.goal == rhs.goal &&
    lhs.preserve_message_height == rhs.preserve_message_height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::general_planner::NavigationGoalRequest_<ContainerAllocator1> & lhs, const ::general_planner::NavigationGoalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace general_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::general_planner::NavigationGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::general_planner::NavigationGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::NavigationGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::NavigationGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::NavigationGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::NavigationGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::general_planner::NavigationGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81e04f6973f6b6d518738090d3369452";
  }

  static const char* value(const ::general_planner::NavigationGoalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81e04f6973f6b6d5ULL;
  static const uint64_t static_value2 = 0x18738090d3369452ULL;
};

template<class ContainerAllocator>
struct DataType< ::general_planner::NavigationGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "general_planner/NavigationGoalRequest";
  }

  static const char* value(const ::general_planner::NavigationGoalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::general_planner::NavigationGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 task_epoch\n"
"uint64 request_id\n"
"geometry_msgs/PoseStamped goal\n"
"bool preserve_message_height\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::general_planner::NavigationGoalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::general_planner::NavigationGoalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_epoch);
      stream.next(m.request_id);
      stream.next(m.goal);
      stream.next(m.preserve_message_height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigationGoalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::general_planner::NavigationGoalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::general_planner::NavigationGoalRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "task_epoch: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.task_epoch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "request_id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.request_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal: ";
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "preserve_message_height: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.preserve_message_height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GENERAL_PLANNER_MESSAGE_NAVIGATIONGOALREQUEST_H
