// Generated by gencpp from file general_planner/PlannerStatus.msg
// DO NOT EDIT!


#ifndef GENERAL_PLANNER_MESSAGE_PLANNERSTATUS_H
#define GENERAL_PLANNER_MESSAGE_PLANNERSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace general_planner
{
template <class ContainerAllocator>
struct PlannerStatus_
{
  typedef PlannerStatus_<ContainerAllocator> Type;

  PlannerStatus_()
    : header()
    , transition_id(0)
    , task_epoch(0)
    , world_epoch(0)
    , map_revision(0)
    , topo_revision(0)
    , accepted_request_id(0)
    , task_id()
    , active_mode(0)
    , requested_mode(0)
    , phase(0)
    , mode_state(0)
    , task_result(0)
    , active_mode_str()
    , requested_mode_str()
    , phase_str()
    , mode_state_str()
    , command_owner_str()
    , task_result_str()
    , stable_hover(false)
    , ready_for_new_task(false)
    , odom_valid(false)
    , map_ready(false)
    , topology_ready(false)
    , command_owner(0)
    , speed_mps(0.0)
    , yaw_rate_rps(0.0)
    , reason()  {
    }
  PlannerStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , transition_id(0)
    , task_epoch(0)
    , world_epoch(0)
    , map_revision(0)
    , topo_revision(0)
    , accepted_request_id(0)
    , task_id(_alloc)
    , active_mode(0)
    , requested_mode(0)
    , phase(0)
    , mode_state(0)
    , task_result(0)
    , active_mode_str(_alloc)
    , requested_mode_str(_alloc)
    , phase_str(_alloc)
    , mode_state_str(_alloc)
    , command_owner_str(_alloc)
    , task_result_str(_alloc)
    , stable_hover(false)
    , ready_for_new_task(false)
    , odom_valid(false)
    , map_ready(false)
    , topology_ready(false)
    , command_owner(0)
    , speed_mps(0.0)
    , yaw_rate_rps(0.0)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _transition_id_type;
  _transition_id_type transition_id;

   typedef uint64_t _task_epoch_type;
  _task_epoch_type task_epoch;

   typedef uint64_t _world_epoch_type;
  _world_epoch_type world_epoch;

   typedef uint64_t _map_revision_type;
  _map_revision_type map_revision;

   typedef uint64_t _topo_revision_type;
  _topo_revision_type topo_revision;

   typedef uint64_t _accepted_request_id_type;
  _accepted_request_id_type accepted_request_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_id_type;
  _task_id_type task_id;

   typedef uint8_t _active_mode_type;
  _active_mode_type active_mode;

   typedef uint8_t _requested_mode_type;
  _requested_mode_type requested_mode;

   typedef uint8_t _phase_type;
  _phase_type phase;

   typedef uint16_t _mode_state_type;
  _mode_state_type mode_state;

   typedef uint8_t _task_result_type;
  _task_result_type task_result;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _active_mode_str_type;
  _active_mode_str_type active_mode_str;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _requested_mode_str_type;
  _requested_mode_str_type requested_mode_str;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _phase_str_type;
  _phase_str_type phase_str;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mode_state_str_type;
  _mode_state_str_type mode_state_str;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_owner_str_type;
  _command_owner_str_type command_owner_str;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_result_str_type;
  _task_result_str_type task_result_str;

   typedef uint8_t _stable_hover_type;
  _stable_hover_type stable_hover;

   typedef uint8_t _ready_for_new_task_type;
  _ready_for_new_task_type ready_for_new_task;

   typedef uint8_t _odom_valid_type;
  _odom_valid_type odom_valid;

   typedef uint8_t _map_ready_type;
  _map_ready_type map_ready;

   typedef uint8_t _topology_ready_type;
  _topology_ready_type topology_ready;

   typedef uint8_t _command_owner_type;
  _command_owner_type command_owner;

   typedef float _speed_mps_type;
  _speed_mps_type speed_mps;

   typedef float _yaw_rate_rps_type;
  _yaw_rate_rps_type yaw_rate_rps;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(MODE_HOLD)
  #undef MODE_HOLD
#endif
#if defined(_WIN32) && defined(MODE_STATE2STATE)
  #undef MODE_STATE2STATE
#endif
#if defined(_WIN32) && defined(MODE_EXPLORATION)
  #undef MODE_EXPLORATION
#endif
#if defined(_WIN32) && defined(MODE_EMERGENCY_STOP)
  #undef MODE_EMERGENCY_STOP
#endif
#if defined(_WIN32) && defined(MODE_TARGET_EXPLORATION)
  #undef MODE_TARGET_EXPLORATION
#endif
#if defined(_WIN32) && defined(PHASE_BOOT)
  #undef PHASE_BOOT
#endif
#if defined(_WIN32) && defined(PHASE_WAITING_INPUT)
  #undef PHASE_WAITING_INPUT
#endif
#if defined(_WIN32) && defined(PHASE_PLANNING)
  #undef PHASE_PLANNING
#endif
#if defined(_WIN32) && defined(PHASE_EXECUTING)
  #undef PHASE_EXECUTING
#endif
#if defined(_WIN32) && defined(PHASE_BRAKING)
  #undef PHASE_BRAKING
#endif
#if defined(_WIN32) && defined(PHASE_HOLD_VERIFY)
  #undef PHASE_HOLD_VERIFY
#endif
#if defined(_WIN32) && defined(PHASE_STABLE_HOLD)
  #undef PHASE_STABLE_HOLD
#endif
#if defined(_WIN32) && defined(PHASE_FAILED)
  #undef PHASE_FAILED
#endif
#if defined(_WIN32) && defined(PHASE_EMERGENCY)
  #undef PHASE_EMERGENCY
#endif
#if defined(_WIN32) && defined(RESULT_NONE)
  #undef RESULT_NONE
#endif
#if defined(_WIN32) && defined(RESULT_SUCCEEDED)
  #undef RESULT_SUCCEEDED
#endif
#if defined(_WIN32) && defined(RESULT_FAILED)
  #undef RESULT_FAILED
#endif
#if defined(_WIN32) && defined(RESULT_CANCELED)
  #undef RESULT_CANCELED
#endif
#if defined(_WIN32) && defined(RESULT_BLOCKED)
  #undef RESULT_BLOCKED
#endif
#if defined(_WIN32) && defined(OWNER_HOLD)
  #undef OWNER_HOLD
#endif
#if defined(_WIN32) && defined(OWNER_STATE2STATE)
  #undef OWNER_STATE2STATE
#endif
#if defined(_WIN32) && defined(OWNER_EXPLORATION)
  #undef OWNER_EXPLORATION
#endif
#if defined(_WIN32) && defined(MODE_STATE_UNKNOWN)
  #undef MODE_STATE_UNKNOWN
#endif
#if defined(_WIN32) && defined(MODE_STATE_S2S_WAIT_GOAL)
  #undef MODE_STATE_S2S_WAIT_GOAL
#endif
#if defined(_WIN32) && defined(MODE_STATE_S2S_GENERATE_TRAJ)
  #undef MODE_STATE_S2S_GENERATE_TRAJ
#endif
#if defined(_WIN32) && defined(MODE_STATE_S2S_FOLLOW_TRAJ)
  #undef MODE_STATE_S2S_FOLLOW_TRAJ
#endif
#if defined(_WIN32) && defined(MODE_STATE_S2S_YAWING)
  #undef MODE_STATE_S2S_YAWING
#endif
#if defined(_WIN32) && defined(MODE_STATE_S2S_EMER_STOP)
  #undef MODE_STATE_S2S_EMER_STOP
#endif
#if defined(_WIN32) && defined(MODE_STATE_EXP_INIT)
  #undef MODE_STATE_EXP_INIT
#endif
#if defined(_WIN32) && defined(MODE_STATE_EXP_WAIT_TRIGGER)
  #undef MODE_STATE_EXP_WAIT_TRIGGER
#endif
#if defined(_WIN32) && defined(MODE_STATE_EXP_PLAN_TRAJ)
  #undef MODE_STATE_EXP_PLAN_TRAJ
#endif
#if defined(_WIN32) && defined(MODE_STATE_EXP_EXEC_TRAJ)
  #undef MODE_STATE_EXP_EXEC_TRAJ
#endif
#if defined(_WIN32) && defined(MODE_STATE_EXP_REORIENT)
  #undef MODE_STATE_EXP_REORIENT
#endif
#if defined(_WIN32) && defined(MODE_STATE_EXP_CAUTION)
  #undef MODE_STATE_EXP_CAUTION
#endif
#if defined(_WIN32) && defined(MODE_STATE_EXP_PAUSING)
  #undef MODE_STATE_EXP_PAUSING
#endif
#if defined(_WIN32) && defined(MODE_STATE_EXP_PAUSED)
  #undef MODE_STATE_EXP_PAUSED
#endif
#if defined(_WIN32) && defined(MODE_STATE_EXP_FINISH)
  #undef MODE_STATE_EXP_FINISH
#endif
#if defined(_WIN32) && defined(MODE_STATE_EXP_WAIT_TARGET)
  #undef MODE_STATE_EXP_WAIT_TARGET
#endif
#if defined(_WIN32) && defined(MODE_STATE_HOLD_IDLE)
  #undef MODE_STATE_HOLD_IDLE
#endif

  enum {
    MODE_HOLD = 0u,
    MODE_STATE2STATE = 1u,
    MODE_EXPLORATION = 2u,
    MODE_EMERGENCY_STOP = 3u,
    MODE_TARGET_EXPLORATION = 4u,
    PHASE_BOOT = 0u,
    PHASE_WAITING_INPUT = 1u,
    PHASE_PLANNING = 2u,
    PHASE_EXECUTING = 3u,
    PHASE_BRAKING = 4u,
    PHASE_HOLD_VERIFY = 5u,
    PHASE_STABLE_HOLD = 6u,
    PHASE_FAILED = 7u,
    PHASE_EMERGENCY = 8u,
    RESULT_NONE = 0u,
    RESULT_SUCCEEDED = 1u,
    RESULT_FAILED = 2u,
    RESULT_CANCELED = 3u,
    RESULT_BLOCKED = 4u,
    OWNER_HOLD = 0u,
    OWNER_STATE2STATE = 1u,
    OWNER_EXPLORATION = 2u,
    MODE_STATE_UNKNOWN = 0u,
    MODE_STATE_S2S_WAIT_GOAL = 1u,
    MODE_STATE_S2S_GENERATE_TRAJ = 2u,
    MODE_STATE_S2S_FOLLOW_TRAJ = 3u,
    MODE_STATE_S2S_YAWING = 4u,
    MODE_STATE_S2S_EMER_STOP = 5u,
    MODE_STATE_EXP_INIT = 10u,
    MODE_STATE_EXP_WAIT_TRIGGER = 11u,
    MODE_STATE_EXP_PLAN_TRAJ = 12u,
    MODE_STATE_EXP_EXEC_TRAJ = 13u,
    MODE_STATE_EXP_REORIENT = 14u,
    MODE_STATE_EXP_CAUTION = 15u,
    MODE_STATE_EXP_PAUSING = 16u,
    MODE_STATE_EXP_PAUSED = 17u,
    MODE_STATE_EXP_FINISH = 18u,
    MODE_STATE_EXP_WAIT_TARGET = 19u,
    MODE_STATE_HOLD_IDLE = 20u,
  };


  typedef boost::shared_ptr< ::general_planner::PlannerStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::general_planner::PlannerStatus_<ContainerAllocator> const> ConstPtr;

}; // struct PlannerStatus_

typedef ::general_planner::PlannerStatus_<std::allocator<void> > PlannerStatus;

typedef boost::shared_ptr< ::general_planner::PlannerStatus > PlannerStatusPtr;
typedef boost::shared_ptr< ::general_planner::PlannerStatus const> PlannerStatusConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::general_planner::PlannerStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::general_planner::PlannerStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::general_planner::PlannerStatus_<ContainerAllocator1> & lhs, const ::general_planner::PlannerStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.transition_id == rhs.transition_id &&
    lhs.task_epoch == rhs.task_epoch &&
    lhs.world_epoch == rhs.world_epoch &&
    lhs.map_revision == rhs.map_revision &&
    lhs.topo_revision == rhs.topo_revision &&
    lhs.accepted_request_id == rhs.accepted_request_id &&
    lhs.task_id == rhs.task_id &&
    lhs.active_mode == rhs.active_mode &&
    lhs.requested_mode == rhs.requested_mode &&
    lhs.phase == rhs.phase &&
    lhs.mode_state == rhs.mode_state &&
    lhs.task_result == rhs.task_result &&
    lhs.active_mode_str == rhs.active_mode_str &&
    lhs.requested_mode_str == rhs.requested_mode_str &&
    lhs.phase_str == rhs.phase_str &&
    lhs.mode_state_str == rhs.mode_state_str &&
    lhs.command_owner_str == rhs.command_owner_str &&
    lhs.task_result_str == rhs.task_result_str &&
    lhs.stable_hover == rhs.stable_hover &&
    lhs.ready_for_new_task == rhs.ready_for_new_task &&
    lhs.odom_valid == rhs.odom_valid &&
    lhs.map_ready == rhs.map_ready &&
    lhs.topology_ready == rhs.topology_ready &&
    lhs.command_owner == rhs.command_owner &&
    lhs.speed_mps == rhs.speed_mps &&
    lhs.yaw_rate_rps == rhs.yaw_rate_rps &&
    lhs.reason == rhs.reason;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::general_planner::PlannerStatus_<ContainerAllocator1> & lhs, const ::general_planner::PlannerStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace general_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::general_planner::PlannerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::general_planner::PlannerStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::PlannerStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::PlannerStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::PlannerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::PlannerStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::general_planner::PlannerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9fd8af440394371ec67478bc266019d";
  }

  static const char* value(const ::general_planner::PlannerStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9fd8af440394371ULL;
  static const uint64_t static_value2 = 0xec67478bc266019dULL;
};

template<class ContainerAllocator>
struct DataType< ::general_planner::PlannerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "general_planner/PlannerStatus";
  }

  static const char* value(const ::general_planner::PlannerStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::general_planner::PlannerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint64 transition_id\n"
"uint64 task_epoch\n"
"uint64 world_epoch\n"
"uint64 map_revision\n"
"uint64 topo_revision\n"
"uint64 accepted_request_id\n"
"\n"
"string task_id\n"
"uint8 active_mode\n"
"uint8 requested_mode\n"
"uint8 phase\n"
"uint16 mode_state\n"
"uint8 task_result\n"
"\n"
"# Human-readable mirrors of the enums above for rostopic echo / upper layers.\n"
"string active_mode_str\n"
"string requested_mode_str\n"
"string phase_str\n"
"string mode_state_str\n"
"string command_owner_str\n"
"string task_result_str\n"
"\n"
"bool stable_hover\n"
"bool ready_for_new_task\n"
"bool odom_valid\n"
"bool map_ready\n"
"bool topology_ready\n"
"uint8 command_owner\n"
"float32 speed_mps\n"
"float32 yaw_rate_rps\n"
"string reason\n"
"\n"
"uint8 MODE_HOLD=0\n"
"uint8 MODE_STATE2STATE=1\n"
"uint8 MODE_EXPLORATION=2\n"
"uint8 MODE_EMERGENCY_STOP=3\n"
"uint8 MODE_TARGET_EXPLORATION=4\n"
"\n"
"uint8 PHASE_BOOT=0\n"
"uint8 PHASE_WAITING_INPUT=1\n"
"uint8 PHASE_PLANNING=2\n"
"uint8 PHASE_EXECUTING=3\n"
"uint8 PHASE_BRAKING=4\n"
"uint8 PHASE_HOLD_VERIFY=5\n"
"uint8 PHASE_STABLE_HOLD=6\n"
"uint8 PHASE_FAILED=7\n"
"uint8 PHASE_EMERGENCY=8\n"
"\n"
"uint8 RESULT_NONE=0\n"
"uint8 RESULT_SUCCEEDED=1\n"
"uint8 RESULT_FAILED=2\n"
"uint8 RESULT_CANCELED=3\n"
"uint8 RESULT_BLOCKED=4\n"
"\n"
"uint8 OWNER_HOLD=0\n"
"uint8 OWNER_STATE2STATE=1\n"
"uint8 OWNER_EXPLORATION=2\n"
"\n"
"uint16 MODE_STATE_UNKNOWN=0\n"
"uint16 MODE_STATE_S2S_WAIT_GOAL=1\n"
"uint16 MODE_STATE_S2S_GENERATE_TRAJ=2\n"
"uint16 MODE_STATE_S2S_FOLLOW_TRAJ=3\n"
"uint16 MODE_STATE_S2S_YAWING=4\n"
"uint16 MODE_STATE_S2S_EMER_STOP=5\n"
"uint16 MODE_STATE_EXP_INIT=10\n"
"uint16 MODE_STATE_EXP_WAIT_TRIGGER=11\n"
"uint16 MODE_STATE_EXP_PLAN_TRAJ=12\n"
"uint16 MODE_STATE_EXP_EXEC_TRAJ=13\n"
"uint16 MODE_STATE_EXP_REORIENT=14\n"
"uint16 MODE_STATE_EXP_CAUTION=15\n"
"uint16 MODE_STATE_EXP_PAUSING=16\n"
"uint16 MODE_STATE_EXP_PAUSED=17\n"
"uint16 MODE_STATE_EXP_FINISH=18\n"
"uint16 MODE_STATE_EXP_WAIT_TARGET=19\n"
"uint16 MODE_STATE_HOLD_IDLE=20\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::general_planner::PlannerStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::general_planner::PlannerStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.transition_id);
      stream.next(m.task_epoch);
      stream.next(m.world_epoch);
      stream.next(m.map_revision);
      stream.next(m.topo_revision);
      stream.next(m.accepted_request_id);
      stream.next(m.task_id);
      stream.next(m.active_mode);
      stream.next(m.requested_mode);
      stream.next(m.phase);
      stream.next(m.mode_state);
      stream.next(m.task_result);
      stream.next(m.active_mode_str);
      stream.next(m.requested_mode_str);
      stream.next(m.phase_str);
      stream.next(m.mode_state_str);
      stream.next(m.command_owner_str);
      stream.next(m.task_result_str);
      stream.next(m.stable_hover);
      stream.next(m.ready_for_new_task);
      stream.next(m.odom_valid);
      stream.next(m.map_ready);
      stream.next(m.topology_ready);
      stream.next(m.command_owner);
      stream.next(m.speed_mps);
      stream.next(m.yaw_rate_rps);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlannerStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::general_planner::PlannerStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::general_planner::PlannerStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "transition_id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.transition_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_epoch: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.task_epoch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "world_epoch: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.world_epoch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_revision: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.map_revision);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "topo_revision: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.topo_revision);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "accepted_request_id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.accepted_request_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "active_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.active_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "requested_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.requested_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "phase: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.phase);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mode_state: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.mode_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.task_result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "active_mode_str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.active_mode_str);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "requested_mode_str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.requested_mode_str);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "phase_str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.phase_str);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mode_state_str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mode_state_str);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "command_owner_str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command_owner_str);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_result_str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_result_str);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stable_hover: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stable_hover);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ready_for_new_task: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ready_for_new_task);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "odom_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.odom_valid);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_ready: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.map_ready);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "topology_ready: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.topology_ready);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "command_owner: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command_owner);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "speed_mps: ";
    Printer<float>::stream(s, indent + "  ", v.speed_mps);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw_rate_rps: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate_rps);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GENERAL_PLANNER_MESSAGE_PLANNERSTATUS_H
