// Generated by gencpp from file general_planner/PlannerPositionCommand.msg
// DO NOT EDIT!


#ifndef GENERAL_PLANNER_MESSAGE_PLANNERPOSITIONCOMMAND_H
#define GENERAL_PLANNER_MESSAGE_PLANNERPOSITIONCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <quadrotor_msgs/PositionCommand.h>

namespace general_planner
{
template <class ContainerAllocator>
struct PlannerPositionCommand_
{
  typedef PlannerPositionCommand_<ContainerAllocator> Type;

  PlannerPositionCommand_()
    : task_epoch(0)
    , task_id()
    , command()  {
    }
  PlannerPositionCommand_(const ContainerAllocator& _alloc)
    : task_epoch(0)
    , task_id(_alloc)
    , command(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _task_epoch_type;
  _task_epoch_type task_epoch;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_id_type;
  _task_id_type task_id;

   typedef  ::quadrotor_msgs::PositionCommand_<ContainerAllocator>  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::general_planner::PlannerPositionCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::general_planner::PlannerPositionCommand_<ContainerAllocator> const> ConstPtr;

}; // struct PlannerPositionCommand_

typedef ::general_planner::PlannerPositionCommand_<std::allocator<void> > PlannerPositionCommand;

typedef boost::shared_ptr< ::general_planner::PlannerPositionCommand > PlannerPositionCommandPtr;
typedef boost::shared_ptr< ::general_planner::PlannerPositionCommand const> PlannerPositionCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::general_planner::PlannerPositionCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::general_planner::PlannerPositionCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::general_planner::PlannerPositionCommand_<ContainerAllocator1> & lhs, const ::general_planner::PlannerPositionCommand_<ContainerAllocator2> & rhs)
{
  return lhs.task_epoch == rhs.task_epoch &&
    lhs.task_id == rhs.task_id &&
    lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::general_planner::PlannerPositionCommand_<ContainerAllocator1> & lhs, const ::general_planner::PlannerPositionCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace general_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::general_planner::PlannerPositionCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::general_planner::PlannerPositionCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::PlannerPositionCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::PlannerPositionCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::PlannerPositionCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::PlannerPositionCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::general_planner::PlannerPositionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06c1da0d31974e4b608776eaa913c7e8";
  }

  static const char* value(const ::general_planner::PlannerPositionCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06c1da0d31974e4bULL;
  static const uint64_t static_value2 = 0x608776eaa913c7e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::general_planner::PlannerPositionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "general_planner/PlannerPositionCommand";
  }

  static const char* value(const ::general_planner::PlannerPositionCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::general_planner::PlannerPositionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 task_epoch\n"
"string task_id\n"
"quadrotor_msgs/PositionCommand command\n"
"\n"
"================================================================================\n"
"MSG: quadrotor_msgs/PositionCommand\n"
"Header header\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 acceleration\n"
"geometry_msgs/Vector3 jerk\n"
"geometry_msgs/Vector3 angular_velocity\n"
"geometry_msgs/Vector3 attitude\n"
"geometry_msgs/Vector3 thrust\n"
"float64 yaw\n"
"float64 yaw_dot\n"
"float64 vel_norm\n"
"float64 acc_norm\n"
"\n"
"\n"
"float64[3] kx\n"
"float64[3] kv\n"
"uint32 trajectory_id\n"
"uint8 TRAJECTORY_STATUS_EMPTY = 0\n"
"uint8 TRAJECTORY_STATUS_EMER = 2\n"
"uint8 TRAJECTORY_STATUS_READY = 1\n"
"uint8 TRAJECTORY_STATUS_COMPLETED = 3\n"
"uint8 TRAJECTROY_STATUS_ABORT = 4\n"
"uint8 TRAJECTORY_STATUS_ILLEGAL_START = 5\n"
"uint8 TRAJECTORY_STATUS_ILLEGAL_FINAL = 6\n"
"uint8 TRAJECTORY_STATUS_IMPOSSIBLE = 7\n"
"uint32 ACTION_STOP                 =   8\n"
"# Its ID number will start from 1, allowing you comparing it with 0.\n"
"uint8 trajectory_flag\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::general_planner::PlannerPositionCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::general_planner::PlannerPositionCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_epoch);
      stream.next(m.task_id);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlannerPositionCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::general_planner::PlannerPositionCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::general_planner::PlannerPositionCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "task_epoch: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.task_epoch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "command: ";
    Printer< ::quadrotor_msgs::PositionCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GENERAL_PLANNER_MESSAGE_PLANNERPOSITIONCOMMAND_H
