// Generated by gencpp from file general_planner/TargetExplorationStatus.msg
// DO NOT EDIT!


#ifndef GENERAL_PLANNER_MESSAGE_TARGETEXPLORATIONSTATUS_H
#define GENERAL_PLANNER_MESSAGE_TARGETEXPLORATIONSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace general_planner
{
template <class ContainerAllocator>
struct TargetExplorationStatus_
{
  typedef TargetExplorationStatus_<ContainerAllocator> Type;

  TargetExplorationStatus_()
    : header()
    , task_epoch(0)
    , task_id()
    , result(0)
    , reason()  {
    }
  TargetExplorationStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , task_epoch(0)
    , task_id(_alloc)
    , result(0)
    , reason(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _task_epoch_type;
  _task_epoch_type task_epoch;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_id_type;
  _task_id_type task_id;

   typedef uint8_t _result_type;
  _result_type result;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(RUNNING)
  #undef RUNNING
#endif
#if defined(_WIN32) && defined(SUCCEEDED)
  #undef SUCCEEDED
#endif
#if defined(_WIN32) && defined(FAILED)
  #undef FAILED
#endif
#if defined(_WIN32) && defined(READY)
  #undef READY
#endif

  enum {
    RUNNING = 0u,
    SUCCEEDED = 1u,
    FAILED = 2u,
    READY = 3u,
  };


  typedef boost::shared_ptr< ::general_planner::TargetExplorationStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::general_planner::TargetExplorationStatus_<ContainerAllocator> const> ConstPtr;

}; // struct TargetExplorationStatus_

typedef ::general_planner::TargetExplorationStatus_<std::allocator<void> > TargetExplorationStatus;

typedef boost::shared_ptr< ::general_planner::TargetExplorationStatus > TargetExplorationStatusPtr;
typedef boost::shared_ptr< ::general_planner::TargetExplorationStatus const> TargetExplorationStatusConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::general_planner::TargetExplorationStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::general_planner::TargetExplorationStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::general_planner::TargetExplorationStatus_<ContainerAllocator1> & lhs, const ::general_planner::TargetExplorationStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.task_epoch == rhs.task_epoch &&
    lhs.task_id == rhs.task_id &&
    lhs.result == rhs.result &&
    lhs.reason == rhs.reason;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::general_planner::TargetExplorationStatus_<ContainerAllocator1> & lhs, const ::general_planner::TargetExplorationStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace general_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::general_planner::TargetExplorationStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::general_planner::TargetExplorationStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::TargetExplorationStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::TargetExplorationStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::TargetExplorationStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::TargetExplorationStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::general_planner::TargetExplorationStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13cde4147ebf5e2ae680eb219ebaa037";
  }

  static const char* value(const ::general_planner::TargetExplorationStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13cde4147ebf5e2aULL;
  static const uint64_t static_value2 = 0xe680eb219ebaa037ULL;
};

template<class ContainerAllocator>
struct DataType< ::general_planner::TargetExplorationStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "general_planner/TargetExplorationStatus";
  }

  static const char* value(const ::general_planner::TargetExplorationStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::general_planner::TargetExplorationStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint64 task_epoch\n"
"string task_id\n"
"\n"
"# Only SUCCEEDED and READY permit dispatching a new target task.\n"
"uint8 RUNNING=0\n"
"uint8 SUCCEEDED=1\n"
"uint8 FAILED=2\n"
"uint8 READY=3\n"
"uint8 result\n"
"string reason\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::general_planner::TargetExplorationStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::general_planner::TargetExplorationStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.task_epoch);
      stream.next(m.task_id);
      stream.next(m.result);
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetExplorationStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::general_planner::TargetExplorationStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::general_planner::TargetExplorationStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_epoch: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.task_epoch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GENERAL_PLANNER_MESSAGE_TARGETEXPLORATIONSTATUS_H
