// Generated by gencpp from file general_planner/TopologyExpansionPoint.msg
// DO NOT EDIT!


#ifndef GENERAL_PLANNER_MESSAGE_TOPOLOGYEXPANSIONPOINT_H
#define GENERAL_PLANNER_MESSAGE_TOPOLOGYEXPANSIONPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace general_planner
{
template <class ContainerAllocator>
struct TopologyExpansionPoint_
{
  typedef TopologyExpansionPoint_<ContainerAllocator> Type;

  TopologyExpansionPoint_()
    : id(0)
    , position()
    , clearance(0.0)
    , degree(0)
    , state(0)
    , is_expandable(false)
    , portal_mask(0)
    , expansion_mask(0)
    , node_revision(0)
    , last_observed_revision(0)  {
    }
  TopologyExpansionPoint_(const ContainerAllocator& _alloc)
    : id(0)
    , position(_alloc)
    , clearance(0.0)
    , degree(0)
    , state(0)
    , is_expandable(false)
    , portal_mask(0)
    , expansion_mask(0)
    , node_revision(0)
    , last_observed_revision(0)  {
  (void)_alloc;
    }



   typedef uint64_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef float _clearance_type;
  _clearance_type clearance;

   typedef uint32_t _degree_type;
  _degree_type degree;

   typedef uint8_t _state_type;
  _state_type state;

   typedef uint8_t _is_expandable_type;
  _is_expandable_type is_expandable;

   typedef uint8_t _portal_mask_type;
  _portal_mask_type portal_mask;

   typedef uint8_t _expansion_mask_type;
  _expansion_mask_type expansion_mask;

   typedef uint64_t _node_revision_type;
  _node_revision_type node_revision;

   typedef uint64_t _last_observed_revision_type;
  _last_observed_revision_type last_observed_revision;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STATE_ACTIVE)
  #undef STATE_ACTIVE
#endif
#if defined(_WIN32) && defined(STATE_HISTORICAL)
  #undef STATE_HISTORICAL
#endif
#if defined(_WIN32) && defined(FACE_NEG_X)
  #undef FACE_NEG_X
#endif
#if defined(_WIN32) && defined(FACE_POS_X)
  #undef FACE_POS_X
#endif
#if defined(_WIN32) && defined(FACE_NEG_Y)
  #undef FACE_NEG_Y
#endif
#if defined(_WIN32) && defined(FACE_POS_Y)
  #undef FACE_POS_Y
#endif
#if defined(_WIN32) && defined(FACE_NEG_Z)
  #undef FACE_NEG_Z
#endif
#if defined(_WIN32) && defined(FACE_POS_Z)
  #undef FACE_POS_Z
#endif

  enum {
    STATE_ACTIVE = 0u,
    STATE_HISTORICAL = 1u,
    FACE_NEG_X = 1u,
    FACE_POS_X = 2u,
    FACE_NEG_Y = 4u,
    FACE_POS_Y = 8u,
    FACE_NEG_Z = 16u,
    FACE_POS_Z = 32u,
  };


  typedef boost::shared_ptr< ::general_planner::TopologyExpansionPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::general_planner::TopologyExpansionPoint_<ContainerAllocator> const> ConstPtr;

}; // struct TopologyExpansionPoint_

typedef ::general_planner::TopologyExpansionPoint_<std::allocator<void> > TopologyExpansionPoint;

typedef boost::shared_ptr< ::general_planner::TopologyExpansionPoint > TopologyExpansionPointPtr;
typedef boost::shared_ptr< ::general_planner::TopologyExpansionPoint const> TopologyExpansionPointConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::general_planner::TopologyExpansionPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::general_planner::TopologyExpansionPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::general_planner::TopologyExpansionPoint_<ContainerAllocator1> & lhs, const ::general_planner::TopologyExpansionPoint_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.position == rhs.position &&
    lhs.clearance == rhs.clearance &&
    lhs.degree == rhs.degree &&
    lhs.state == rhs.state &&
    lhs.is_expandable == rhs.is_expandable &&
    lhs.portal_mask == rhs.portal_mask &&
    lhs.expansion_mask == rhs.expansion_mask &&
    lhs.node_revision == rhs.node_revision &&
    lhs.last_observed_revision == rhs.last_observed_revision;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::general_planner::TopologyExpansionPoint_<ContainerAllocator1> & lhs, const ::general_planner::TopologyExpansionPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace general_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::general_planner::TopologyExpansionPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::general_planner::TopologyExpansionPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::TopologyExpansionPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::TopologyExpansionPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::TopologyExpansionPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::TopologyExpansionPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::general_planner::TopologyExpansionPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a30150b5dfd7e2580c24f58d1a56aef";
  }

  static const char* value(const ::general_planner::TopologyExpansionPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a30150b5dfd7e25ULL;
  static const uint64_t static_value2 = 0x80c24f58d1a56aefULL;
};

template<class ContainerAllocator>
struct DataType< ::general_planner::TopologyExpansionPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "general_planner/TopologyExpansionPoint";
  }

  static const char* value(const ::general_planner::TopologyExpansionPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::general_planner::TopologyExpansionPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A persistent global-topology node exposed as a frontier-equivalent point.\n"
"# `is_expandable` means that at least one selected portal face has no active\n"
"# topology edge to an adjacent region. It is a topology-growth candidate, not\n"
"# a guarantee that the corresponding map direction is traversable.\n"
"\n"
"uint64 id\n"
"geometry_msgs/Point position\n"
"float32 clearance\n"
"uint32 degree\n"
"uint8 state\n"
"bool is_expandable\n"
"uint8 portal_mask\n"
"uint8 expansion_mask\n"
"uint64 node_revision\n"
"uint64 last_observed_revision\n"
"\n"
"uint8 STATE_ACTIVE=0\n"
"uint8 STATE_HISTORICAL=1\n"
"\n"
"uint8 FACE_NEG_X=1\n"
"uint8 FACE_POS_X=2\n"
"uint8 FACE_NEG_Y=4\n"
"uint8 FACE_POS_Y=8\n"
"uint8 FACE_NEG_Z=16\n"
"uint8 FACE_POS_Z=32\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::general_planner::TopologyExpansionPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::general_planner::TopologyExpansionPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
      stream.next(m.clearance);
      stream.next(m.degree);
      stream.next(m.state);
      stream.next(m.is_expandable);
      stream.next(m.portal_mask);
      stream.next(m.expansion_mask);
      stream.next(m.node_revision);
      stream.next(m.last_observed_revision);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TopologyExpansionPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::general_planner::TopologyExpansionPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::general_planner::TopologyExpansionPoint_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "clearance: ";
    Printer<float>::stream(s, indent + "  ", v.clearance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "degree: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.degree);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_expandable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_expandable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "portal_mask: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.portal_mask);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "expansion_mask: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.expansion_mask);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "node_revision: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.node_revision);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "last_observed_revision: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.last_observed_revision);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GENERAL_PLANNER_MESSAGE_TOPOLOGYEXPANSIONPOINT_H
