// Generated by gencpp from file general_planner/TopologyExpansionPointArray.msg
// DO NOT EDIT!


#ifndef GENERAL_PLANNER_MESSAGE_TOPOLOGYEXPANSIONPOINTARRAY_H
#define GENERAL_PLANNER_MESSAGE_TOPOLOGYEXPANSIONPOINTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <general_planner/TopologyExpansionPoint.h>

namespace general_planner
{
template <class ContainerAllocator>
struct TopologyExpansionPointArray_
{
  typedef TopologyExpansionPointArray_<ContainerAllocator> Type;

  TopologyExpansionPointArray_()
    : header()
    , world_epoch(0)
    , map_revision(0)
    , topology_revision(0)
    , active_count(0)
    , expandable_count(0)
    , points()  {
    }
  TopologyExpansionPointArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , world_epoch(0)
    , map_revision(0)
    , topology_revision(0)
    , active_count(0)
    , expandable_count(0)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _world_epoch_type;
  _world_epoch_type world_epoch;

   typedef uint64_t _map_revision_type;
  _map_revision_type map_revision;

   typedef uint64_t _topology_revision_type;
  _topology_revision_type topology_revision;

   typedef uint32_t _active_count_type;
  _active_count_type active_count;

   typedef uint32_t _expandable_count_type;
  _expandable_count_type expandable_count;

   typedef std::vector< ::general_planner::TopologyExpansionPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::general_planner::TopologyExpansionPoint_<ContainerAllocator> >> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::general_planner::TopologyExpansionPointArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::general_planner::TopologyExpansionPointArray_<ContainerAllocator> const> ConstPtr;

}; // struct TopologyExpansionPointArray_

typedef ::general_planner::TopologyExpansionPointArray_<std::allocator<void> > TopologyExpansionPointArray;

typedef boost::shared_ptr< ::general_planner::TopologyExpansionPointArray > TopologyExpansionPointArrayPtr;
typedef boost::shared_ptr< ::general_planner::TopologyExpansionPointArray const> TopologyExpansionPointArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::general_planner::TopologyExpansionPointArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::general_planner::TopologyExpansionPointArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::general_planner::TopologyExpansionPointArray_<ContainerAllocator1> & lhs, const ::general_planner::TopologyExpansionPointArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.world_epoch == rhs.world_epoch &&
    lhs.map_revision == rhs.map_revision &&
    lhs.topology_revision == rhs.topology_revision &&
    lhs.active_count == rhs.active_count &&
    lhs.expandable_count == rhs.expandable_count &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::general_planner::TopologyExpansionPointArray_<ContainerAllocator1> & lhs, const ::general_planner::TopologyExpansionPointArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace general_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::general_planner::TopologyExpansionPointArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::general_planner::TopologyExpansionPointArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::TopologyExpansionPointArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_planner::TopologyExpansionPointArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::TopologyExpansionPointArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_planner::TopologyExpansionPointArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::general_planner::TopologyExpansionPointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01c05a9db32d1c49204aa111573db7e2";
  }

  static const char* value(const ::general_planner::TopologyExpansionPointArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01c05a9db32d1c49ULL;
  static const uint64_t static_value2 = 0x204aa111573db7e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::general_planner::TopologyExpansionPointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "general_planner/TopologyExpansionPointArray";
  }

  static const char* value(const ::general_planner::TopologyExpansionPointArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::general_planner::TopologyExpansionPointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Latched, full snapshot of frontier-equivalent persistent topology points.\n"
"\n"
"std_msgs/Header header\n"
"uint64 world_epoch\n"
"uint64 map_revision\n"
"uint64 topology_revision\n"
"uint32 active_count\n"
"uint32 expandable_count\n"
"TopologyExpansionPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: general_planner/TopologyExpansionPoint\n"
"# A persistent global-topology node exposed as a frontier-equivalent point.\n"
"# `is_expandable` means that at least one selected portal face has no active\n"
"# topology edge to an adjacent region. It is a topology-growth candidate, not\n"
"# a guarantee that the corresponding map direction is traversable.\n"
"\n"
"uint64 id\n"
"geometry_msgs/Point position\n"
"float32 clearance\n"
"uint32 degree\n"
"uint8 state\n"
"bool is_expandable\n"
"uint8 portal_mask\n"
"uint8 expansion_mask\n"
"uint64 node_revision\n"
"uint64 last_observed_revision\n"
"\n"
"uint8 STATE_ACTIVE=0\n"
"uint8 STATE_HISTORICAL=1\n"
"\n"
"uint8 FACE_NEG_X=1\n"
"uint8 FACE_POS_X=2\n"
"uint8 FACE_NEG_Y=4\n"
"uint8 FACE_POS_Y=8\n"
"uint8 FACE_NEG_Z=16\n"
"uint8 FACE_POS_Z=32\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::general_planner::TopologyExpansionPointArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::general_planner::TopologyExpansionPointArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.world_epoch);
      stream.next(m.map_revision);
      stream.next(m.topology_revision);
      stream.next(m.active_count);
      stream.next(m.expandable_count);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TopologyExpansionPointArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::general_planner::TopologyExpansionPointArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::general_planner::TopologyExpansionPointArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "world_epoch: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.world_epoch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_revision: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.map_revision);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "topology_revision: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.topology_revision);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "active_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.active_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "expandable_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.expandable_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "points: ";
    if (v.points.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::general_planner::TopologyExpansionPoint_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.points[i]);
    }
    if (v.points.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // GENERAL_PLANNER_MESSAGE_TOPOLOGYEXPANSIONPOINTARRAY_H
