// Generated by gencpp from file aperture_detector/ApertureObservation.msg
// DO NOT EDIT!


#ifndef APERTURE_DETECTOR_MESSAGE_APERTUREOBSERVATION_H
#define APERTURE_DETECTOR_MESSAGE_APERTUREOBSERVATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Polygon.h>

namespace aperture_detector
{
template <class ContainerAllocator>
struct ApertureObservation_
{
  typedef ApertureObservation_<ContainerAllocator> Type;

  ApertureObservation_()
    : header()
    , geometry_valid(false)
    , reason()
    , center()
    , normal()
    , boundary()
    , plane_area(0.0)
    , hole_area(0.0)
    , area_ratio(0.0)
    , visual_roi_used(false)
    , depth_known(false)
    , depth(0.0)  {
    }
  ApertureObservation_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , geometry_valid(false)
    , reason(_alloc)
    , center(_alloc)
    , normal(_alloc)
    , boundary(_alloc)
    , plane_area(0.0)
    , hole_area(0.0)
    , area_ratio(0.0)
    , visual_roi_used(false)
    , depth_known(false)
    , depth(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _geometry_valid_type;
  _geometry_valid_type geometry_valid;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _reason_type;
  _reason_type reason;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _normal_type;
  _normal_type normal;

   typedef  ::geometry_msgs::Polygon_<ContainerAllocator>  _boundary_type;
  _boundary_type boundary;

   typedef double _plane_area_type;
  _plane_area_type plane_area;

   typedef double _hole_area_type;
  _hole_area_type hole_area;

   typedef double _area_ratio_type;
  _area_ratio_type area_ratio;

   typedef uint8_t _visual_roi_used_type;
  _visual_roi_used_type visual_roi_used;

   typedef uint8_t _depth_known_type;
  _depth_known_type depth_known;

   typedef double _depth_type;
  _depth_type depth;





  typedef boost::shared_ptr< ::aperture_detector::ApertureObservation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aperture_detector::ApertureObservation_<ContainerAllocator> const> ConstPtr;

}; // struct ApertureObservation_

typedef ::aperture_detector::ApertureObservation_<std::allocator<void> > ApertureObservation;

typedef boost::shared_ptr< ::aperture_detector::ApertureObservation > ApertureObservationPtr;
typedef boost::shared_ptr< ::aperture_detector::ApertureObservation const> ApertureObservationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aperture_detector::ApertureObservation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aperture_detector::ApertureObservation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aperture_detector::ApertureObservation_<ContainerAllocator1> & lhs, const ::aperture_detector::ApertureObservation_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.geometry_valid == rhs.geometry_valid &&
    lhs.reason == rhs.reason &&
    lhs.center == rhs.center &&
    lhs.normal == rhs.normal &&
    lhs.boundary == rhs.boundary &&
    lhs.plane_area == rhs.plane_area &&
    lhs.hole_area == rhs.hole_area &&
    lhs.area_ratio == rhs.area_ratio &&
    lhs.visual_roi_used == rhs.visual_roi_used &&
    lhs.depth_known == rhs.depth_known &&
    lhs.depth == rhs.depth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aperture_detector::ApertureObservation_<ContainerAllocator1> & lhs, const ::aperture_detector::ApertureObservation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aperture_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::aperture_detector::ApertureObservation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aperture_detector::ApertureObservation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aperture_detector::ApertureObservation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aperture_detector::ApertureObservation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aperture_detector::ApertureObservation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aperture_detector::ApertureObservation_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aperture_detector::ApertureObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95d12957350e43dfd81355376a355b51";
  }

  static const char* value(const ::aperture_detector::ApertureObservation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95d12957350e43dfULL;
  static const uint64_t static_value2 = 0xd81355376a355b51ULL;
};

template<class ContainerAllocator>
struct DataType< ::aperture_detector::ApertureObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aperture_detector/ApertureObservation";
  }

  static const char* value(const ::aperture_detector::ApertureObservation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aperture_detector::ApertureObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Geometry only: validity does not certify vehicle passage or free exit space.\n"
"# stamp is the newest contributing cloud stamp, never a publication timestamp.\n"
"std_msgs/Header header\n"
"bool geometry_valid\n"
"string reason\n"
"geometry_msgs/Point center\n"
"geometry_msgs/Vector3 normal\n"
"geometry_msgs/Polygon boundary\n"
"float64 plane_area\n"
"float64 hole_area\n"
"float64 area_ratio\n"
"bool visual_roi_used\n"
"bool depth_known\n"
"float64 depth\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::aperture_detector::ApertureObservation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aperture_detector::ApertureObservation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.geometry_valid);
      stream.next(m.reason);
      stream.next(m.center);
      stream.next(m.normal);
      stream.next(m.boundary);
      stream.next(m.plane_area);
      stream.next(m.hole_area);
      stream.next(m.area_ratio);
      stream.next(m.visual_roi_used);
      stream.next(m.depth_known);
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ApertureObservation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aperture_detector::ApertureObservation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aperture_detector::ApertureObservation_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "geometry_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.geometry_valid);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.reason);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "center: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "normal: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.normal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "boundary: ";
    Printer< ::geometry_msgs::Polygon_<ContainerAllocator> >::stream(s, indent + "  ", v.boundary);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "plane_area: ";
    Printer<double>::stream(s, indent + "  ", v.plane_area);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "hole_area: ";
    Printer<double>::stream(s, indent + "  ", v.hole_area);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "area_ratio: ";
    Printer<double>::stream(s, indent + "  ", v.area_ratio);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "visual_roi_used: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.visual_roi_used);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "depth_known: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.depth_known);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "depth: ";
    Printer<double>::stream(s, indent + "  ", v.depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // APERTURE_DETECTOR_MESSAGE_APERTUREOBSERVATION_H
